- README.md
- __tests__/address.test.js
- __tests__/encryption.test.js
- __tests__/new_wallet.test.js
- __tests__/tokens_utils.js
- __tests__/transaction_utils.test.js
- __tests__/wallet.test.js
- __tests__/wallet_utils.test.js
- index.js
- package.json
- setupTests.js
- src/WebSocketHandler.js
- src/helpers.js
- src/storage.js
- src/tokens.js
- src/transaction.js
- src/wallet.js
The lib now doesn't require localStorage and clients should pass a storage to the lib using `setStorage()`.
> refactor: stop using localStorage

- src/WebSocketHandler.js
`endConnection` is called in `src/wallet.js` in the method `reloadData`, that is called when unlocking the wallet (desktop), resetting wallet and changing server.
`this.ws` was never being set to null, so it would never connect again.
> fix: ws connection issue

- __tests__/helpers.test.js
- __tests__/tokens_utils.js
- __tests__/transaction_utils.test.js
- __tests__/wallet.test.js
- index.js
- src/api/wallet.js
- src/constants.js
- src/errors.js
- src/helpers.js
- src/memory_store.js
- src/tokens.js
- src/transaction.js
- src/wallet.js
- Adding api to get token info;
- Adding extra validations when a token is registered. Verifying if name and symbol match with the one in the DAG and checking if there is no other token with this name, or symbol already registered;
- Using version field to get transaction type (block, transaction, token creation tx).
> feat: improvements token info

- __tests__/wallet_utils.test.js
- package.json
- src/wallet.js
We actually need xpubkey to always be persisted. As with the latest change in the wallet, `wallet:data` is kept in memory, so it would not persist across restarts.
> fix: move xpubkey to wallet:accessData on storage

- src/new/wallet.js
Even though it's more logical to use `sendTransaction` I didn't want to break compatibility with the other method in case other projects are already using it.
> feat: creating method to send a transaction from an array of outputs

- src/wallet.js
**The problem**
Using clone was probably creating many instances of the store in memory, which were different from the initial one set in the wallet class.
Wallet class:
```
this.store = store
storage.setStore(this.store)
```
Wallet utils:
```
let oldStore = _.clone(store)
...
storage.setStore(oldStore)
```
> refactor: removing store clone when using multiples wallets

- __tests__/websocket.test.js
- src/websocket.js
On the daemon we get no information when a websocket connection fails, the `Connection` class will just silently keep retrying the connection to the fullnode.
On this PR, I will emit a `connection_error` event so the daemon can listen to it and log the connection error
> feat: emitting connection_error if a connection fails

- src/wallet/wallet.ts
The wallet service facade should set the lib network when instantiated
> fix: set correct network on wallet service facade

- src/wallet/sendTransactionWalletService.ts
- src/wallet/wallet.ts
We are executing `calculateWeight` method before setting the input data (with signatures), then the tx weight is smaller than it should be. This error happens only on the wallet service facade and was not happening before because the tests were made only on the testnet and the min_weight is 8 there.
The weight should be calculated fine for the transaction and we must be able to send a transaction using the wallet service on the mainnet.
> fix: we should calculate tx weight after adding input data

- src/utils/helpers.ts
NFTs amounts must be shown as integers instead of decimals. Even showing as integer we still need to format them to show thousand separator, i.e. we must show "10,000" instead of "10000".
We must have a method to show pretty integer value (integer with thousand separator) and this method must be reused by prettyValue method.
> feat: separate method to show prettyValue to use a prettyIntegerValue used by NFTs

- src/new/wallet.js
We must avoid keeping the seed/privkey on memory after it is no longer necessary to load the wallet.
> fix: clear sensitive data after wallet load

- src/constants.js
- src/errors.js
- src/models/create_token_transaction.ts
- src/new/sendTransaction.js
- src/new/wallet.js
- src/tokens.js
- src/transaction.js
- src/utils/helpers.ts
- src/wallet/mineTransaction.ts
- src/wallet/sendTransactionWalletService.ts
- src/wallet/types.ts
I've done 3 different things in this PR
1. fix: error handling in `SendTransaction` class is now working. If we have an error when mining or pushing tx, it will be handled by the promise.
2. feat: add validation for name/symbol size in the CreateTokenTransaction object
3. feat: add address validation in some places we hadn't added it (especially this one will require some changes in the wallets)
> fix: error handling when sending transaction

- src/models/network.ts
- We are using the same version bytes as the Testnet for the private networks, because we would have problems with TxMiningService if using different ones, since it validates the addresses.
> feat: allow private networks

- package-lock.json
- package.json
- Version should be bumped to v0.28.0
> chore: bump to v0.28.0

- src/transaction.js
- Should we create a new parameter to explicitly say that we expect the tx to have inputs from different wallets? And in case we don't trigger this parameter, then we can raise an error if we find an input that does not belong to the wallet loaded?
Atomic swap transactions have inputs that belong to different wallets and the signTx method expects that all inputs are going to be signed by the loaded wallet.
- We must be able to call `signTx` method with a transaction that has inputs from different wallets and the method must sign only the inputs that belong to the loaded wallet.
> feat: sign only inputs that belong to the loaded wallet

- src/new/sendTransaction.js
The `sendTransaction` class prepares and signs the transaction on the same method.
To use this with the hardware wallet we implement the preparation on the wallet and instantiate the `sendTransaction` with the prepared transaction with the signatures from the hardware wallet.
This PR aims to unify this preparation on the wallet-lib, creating the `prepareTxData` that will be used to send the tx to the hardware wallet and `prepareTxFrom` to create the tx from the signatures from the hardware wallet while keeping the same functionality at the `prepareTx` (as to not disturb the functionality of the other wallets that use this method).
- Create a method to prepare the tx data without signing so it can be used by a hardware wallet.
- Create a method to complete the tx with the signatures from …
> feat: split prepare and sign tx

- src/constants.js
- src/utils/wallet.ts
- src/wallet.js
- src/wallet/api/walletApi.ts
- src/wallet/types.ts
- src/wallet/wallet.ts
Implements https://github.com/HathorNetwork/internal-issues/issues/76
- We should use a different derivation from the one used to start the wallet to authenticate requests on the wallet service
- We should prove we own both `xpubs` (the wallet's account level and the auth_xpubkey) on the start wallet API
- We should use the `auth_xpubkey` to request a JWT token from the wallet service
> refactor: using auth xpubkey to authenticate wallet service requests

- __tests__/wallet/api/walletServiceAxios.test.ts
- __tests__/wallet/wallet.test.ts
- src/constants.js
- src/utils/wallet.ts
- src/wallet.js
- src/wallet/api/walletApi.ts
- src/wallet/sendTransactionWalletService.ts
- src/wallet/types.ts
- src/wallet/wallet.ts
- The wallet service facade should remove the seed from memory after the wallet is started
- The wallet service facade should receive a async method to request the pin from the client and use it when needed
- We should renew the auth token everytime the user inputs his PIN, even if it is not expired
> refactor: remove sensitive data (seed) from memory after it is used

- src/connection.ts
- src/new/connection.ts
- src/wallet/connection.ts
- src/wallet/types.ts
- src/wallet/wallet.ts
Currently, the old wallet facade reloads the data from the connected full-node every time the WebSocket is re-established. This is needed because it might have lost a transaction at the time it has been disconnected.
The new wallet-service facade is not doing this at the moment and we can't use the same mechanism the old facade uses as we don't have control of the storage on the new facade on the wallet-lib, so I've created a `reload-data` event that is currently only implemented on the new wallet service facade to indicate to clients that data must be reloaded
- The wallet service facade should emit a `reload-data` event every time the WebSocket connection is re-established.
- The wallet service facade should not emit a `reload-data` event if the connection established event is the first …
> feat: emit reload event after a reconnection

- src/wallet.js
- src/wallet/types.ts
- src/wallet/wallet.ts
`changePin` on the wallet mobile was failing on the wallet service facade because we use the pin as password and we didn't have the `hashPasswd` and `saltPasswd` stored on the `accessData` to be able to validate if it is correct. 
To solve this, we are using the `executeGenerateWallet` method that already existed on `wallet.js`
- `accessData` should be properly initialized with the same data the old facade had
- `changePassword` should be able to validate if the password is correct without crashing
> fix: change password broken on wallet service

- __tests__/wallet/mineTransaction.test.ts
- package.json
- src/api/txMining.js
- src/new/sendTransaction.js
- src/wallet/mineTransaction.ts
The lib should be able no nicely handle Http Code 429 that it may get from tx-mining-service
1. I don't know how I should go about translating the new error message into other languages in wallet-mobile.
2. In wallet-mobile, the message would be stripped:
> feat: handle tx-mining rate limit

- src/api/axiosWrapper.ts
- src/api/txMiningAxios.ts
- src/config.ts
- The lib should allow setting an api-key to be used in requests for tx-mining-service
> feat: allow setting tx mining service apikey

- __tests__/wallet/api/walletServiceAxios.test.ts
- __tests__/wallet/wallet.test.ts
- src/constants.js
- src/new/wallet.js
- src/utils/wallet.ts
- src/wallet.js
- src/wallet/api/walletApi.ts
- src/wallet/types.ts
- src/wallet/wallet.ts
Currently, our wallet desktop is querying the fullnode for token details, we should use the same method on both facades to query this information from the wallet-service (if on the facade) or the full-node. This new method will utilize the token info API, [created on the wallet-service](https://github.com/HathorNetwork/hathor-wallet-service/pull/202)
- We should have a method on both facades to query token details
> feat: get tokens details from both facades

- __tests__/wallet/api/walletServiceAxios.test.ts
- __tests__/wallet/wallet.test.ts
- src/constants.js
- src/new/wallet.js
- src/utils/wallet.ts
- src/wallet.js
- src/wallet/api/walletApi.ts
- src/wallet/types.ts
- src/wallet/wallet.ts
Currently, the wallet service facade expects to always receive a seed to be able to derive the change level path private key it uses to identify each wallet (we use a double sha256 encoded hash of the xpubkey on that path as a `wallet-id`).
The problem is that the `wallet-desktop` expects to be able to start the wallet using an `xprivkey` when restoring an already loaded wallet and a `xpubkey` when using the Hardware Wallet and currently, the `mainKey` stored on the device's local storage is on the change level path, making it impossible for the wallet-service to get the account level path
The idea here is to store a account level path xprivkey on storage, encrypted using the PIN code, every time the wallet is started from the seed and use it when needed
- We should be able to load a …
> feat: wallet service facade should be able to start from a xprivkey on the account path derivation

- src/new/wallet.js
There was a bug in the `selectAuthorityUtxo` logic, if the wallet had at least one spent output for a given token and the method was called with `skipSpent: false`, it would return that spent tx output as if it were a authority utxo
- `selectAuthorityUtxo` should correctly return an empty list if the wallet has no authority utxos and `skipSpent` is false
> fix: select authority utxo returning invalid results when the wallet has at least one spent output

- __tests__/wallet.test.js
- src/new/wallet.js
- src/wallet.js
This PR adds a parameter on the wallet initialization `constructor` and `loadAddressHistory` methods, to allow the caller to pre-calculate a wallet's addresses, saving on processing time for the lib.
This is especially useful for testing environments, and is a required feature of HathorNetwork/hathor-wallet-headless#189
- The wallet init process must be unchanged when the `preCalculatedAddresses` parameter is not informed
- The wallet init must accept the pre-calculated addresses on the new parameter when informed
> feat: adds address precalculation parameter

- __tests__/utils/wallet.test.js
One of the tests of `wordsValid` method was checking that adding a random word from mnemonic wordlist as the last word of the seed would still be invalid. 
The word we were always adding was "word" but sometimes the last word was actually "word", then the test was failing.
> test: words valid test was failing eventually

- __tests__/new_wallet.test.js
- __tests__/utils/wallet.test.js
- __tests__/wallet.test.js
- src/new/wallet.js
- src/utils/wallet.ts
- src/wallet.js
- Rename `minSignatures` to `numSignatures`
- Change the requirement of having minimum of (formerly known as) `minSignatures` to only allowing `numSignatures` when creating a P2SH input data.
> refactor: rename minSignatures to numSignatures

- package-lock.json
- package.json
https://github.com/HathorNetwork/hathor-wallet-lib/pull/258
With the list of version downloads below, I will run some tests using our lib with axios upgraded version v0.21.4, since it's the most downloaded lately and it's already a huge jump from our current version.
We should have another issue to do another upgrade to the latest version soon.
Tests executed:
- We should use axios in v0.21.4.
> chore: bump axios version to v0.21.4

- src/models/partial_tx.ts
- src/wallet/partialTxProposal.ts
- token field is called `tokenId` on `Utxo` type
- allow deserializing `PartialTxInputData` with no signatures
> fix: typo using utxo type

- src/new/wallet.js
- Fixes minor bug on getting full history
- Improves maintainability by reusing `txout` variable
> fix: markUtxoSelected adjustment

- __tests__/hathorwallet.test.js
- __tests__/integration/hathorwallet_facade.test.js
- src/new/wallet.js
- throw error if an xpub wallet calls `getAllSignatures`
> chore: protect getAllSignatures method from xpub wallet access

- __tests__/integration/atomic_swap.test.js
- __tests__/integration/hathorwallet_facade.test.js
- __tests__/token_details.test.js
- src/new/wallet.js
- `getTokenDetails` should throw an error with the message received from the API if `success` is false
> fix: getTokenDetails should throw if success is false

- __tests__/hathorwallet.test.js
- __tests__/integration/hathorwallet_facade.test.js
- __tests__/models/queue.test.js
- jest-integration.config.js
- src/models/queue.ts
- src/new/wallet.js
- Create a queue to process txs that arrived via websocket during initial load
- Process queue after `preProcessWalletData`
- When sync finishes change state to `PROCESSING` instead of `READY`
- `preProcessWalletData` will change state to `READY` when it finishes processing (this includes the ws txs on queue)
> feat: ws processing queue

- __tests__/hathorwallet.test.js
- __tests__/wallet/wallet.test.ts
- src/new/wallet.js
- src/wallet/types.ts
- src/wallet/wallet.ts
- We should return the `version` attribute on transactions history
- `prepareDelegateAuthority` on the wallet-service facade should expect `createAnother` instead of `createAnotherAuthority` param
> fix: version on tx history + createAnother on prepareDelegateAuthority

- src/models/p2pkh.ts
- src/models/p2sh.ts
- src/utils/buffer.ts
- src/utils/wallet.ts
The `offset` parameter is mandatory on the Electron environment for the `readInt__`/`readDouble__` methods on certain conditions.
These conditions happen to us because we have an issue of passing the wrong type of parameter to `unpackToInt` and `unpackToFloat`: instead of Buffers, we're passing them `UInt8Arrays`.
For now, we will just ensure the calls with these parameters don't crash on Electron and keep working as expected, for example, when deserializing an instance of a `PartialTx`.
- Every `readInt__` and `readDouble__` method called on the lib should have an `offset` parameter
> fix: buffer mandatory parameter

- __tests__/wallet/api/swapService.test.ts
- index.js
- src/config.ts
- src/wallet/api/swapService.ts
Implements the initial code for communication with the Atomic Swap Service.
- Hashing and encrypting all data before sending it over to the Atomic Swap Service
- Only the `create` endpoint will be interacted with
No integration tests will be implemented at this stage, as there is no readily available image of the Atomic Swap Service to be added to the `docker-compose.yml` structure necessary for them.
> feat: create endpoint to the atomic swap service

- src/config.ts
The current implementation requires the client applications to duplicate the `mainnet` and `testnet` urls on their codes if one decides to use the `setSwapServiceBaseUrl` method for URL configuration.
This change makes the lib's default values available for them.
- Default Atomic Swap Service URLs should be exported
> fix: client apps should access default swap urls

- package-lock.json
- package.json
- Bump to v0.46.1
- Integration with the Atomic Swap Service backend: `get` endpoint
- Exports Atomic Swap Service default urls for mainnet and testnet
> chore: bump 0.46.1

- __tests__/wallet/api/swapService.test.ts
- src/wallet/api/swapService.ts
Continuation of the Atomic Swap Service integration started on #464 and #468 
- The lib should interact with the `update` endpoint on the Atomic Swap Service
- All original data should be correctly encrypted on sending the data to the backend
No integration tests will be added at this stage, as there is no readily available image of the Atomic Swap Service to be added to the `docker-compose.yml` structure necessary for them.
A partial implementation of these tests, however, is available on branch [`feat/swap-service-integration`](https://github.com/HathorNetwork/hathor-wallet-lib/tree/feat/swap-service-integration) ( [diff with `dev`](https://github.com/HathorNetwork/hathor-wallet-lib/compare/dev...feat/swap-service-integration?expand=1) ) and can be executed on a local environment by …
> feat: swap service `update`

- .github/workflows/integration-test.yml
- .github/workflows/main.yml
- .gitignore
- __tests__/integration/hathorwallet_facade.test.js
- __tests__/integration/hathorwallet_others.test.js
- __tests__/integration/helpers/genesis-wallet.helper.js
- __tests__/integration/storage/leveldb.test.js
- __tests__/storage/leveldb/leveldb_store.test.js
- __tests__/storage/memory_store.test.js
- __tests__/utils/tokens.test.js
- index.js
- package.json
- setupTests.js
- src/api/metadataApi.ts
- src/new/wallet.js
- src/storage/index.ts
- src/storage/leveldb/address_index.ts
- src/storage/leveldb/errors.ts
- src/storage/leveldb/history_index.ts
- src/storage/leveldb/store.ts
- src/storage/leveldb/token_index.ts
- src/storage/leveldb/utxo_index.ts
- src/storage/leveldb/wallet_index.ts
- src/storage/memory_store.ts
- src/types.ts
- src/utils/storage.ts
- src/utils/tokens.ts
- src/wallet/types.ts
- Implement a store of data using LevelDB
- Implement reverse search indexes to comply with the `IStore` interface
- Deprecate node v8 and v10
> feat: persistent storage

- __tests__/storage/leveldb/leveldb_store.test.js
- __tests__/storage/storage.test.js
- __tests__/utils/transaction.test.js
- src/storage/leveldb/utxo_index.ts
- filter for locked utxos only if `only_available_utxos` is true
- filter for timelocks on leveldb
> feat: leveldb filter locked utxos

- .github/workflows/integration-test.yml
Github is deprecating the CI actions versions that use node12 and showing warnings since node12 reached its EOL on april 2022.
- [github changelog](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/)
- [ref to EOL in MS updates](https://azure.microsoft.com/en-us/updates/node12/#:~:text=On%2030%20April%202022%2C%20extended,workloads%20will%20not%20be%20impacted.)
- Upgrade the actions to the most recent version (which uses node16)
> chore: deprecate node12 ci actions

- .github/workflows/integration-test.yml
- .github/workflows/main.yml
- Pin github actions version to the commit sha as suggested by github security docs
> chore: pin 3rd party actions to full commit sha

- src/wallet.js
- `getAcctPathXprivKey` should return null if it doesn't exist in storage
> fix: account path not checking for null before decrypting

- index.js
- Export the `src/wallet/api/walletApi.ts` module as `walletServiceApi` in the lib exports.
> chore: export wallet-service api module

- __tests__/wallet/wallet.test.ts
- src/new/wallet.js
- src/wallet/wallet.ts
- We should allow providing the pinCode in the `HathorWalletServiceWallet's sendTransaction` method. Otherwise, we would get an error of missing pinCode when trying to send a transaction with this method in a wallet that uses a pin code.
> fix: allow providing pinCode when sending transaction with HathorWalletServiceWallet

- __tests__/new/hathorwallet.test.js
- __tests__/storage/storage.test.js
- __tests__/utils/crypto.test.ts
- __tests__/utils/wallet.test.js
- src/new/wallet.js
- src/storage/storage.ts
- src/types.ts
- src/utils/crypto.ts
- src/utils/wallet.ts
- src/wallet/types.ts
- src/wallet/wallet.ts
- Create a method for wallets to check the pin and password
- Create a method for wallets to change the pin and password
> check pin method

- __tests__/integration/storage/leveldb.test.js
- __tests__/integration/storage/storage.test.js
- __tests__/storage/common_store.test.js
- __tests__/storage/leveldb/leveldb_store.test.js
- __tests__/storage/storage.test.js
- __tests__/utils/utxo.test.js
Some tests merged after we changed how we name the leveldb store used the old naming system.
This only affects some tests but when running they will leave a directory with the xpub name instead of creating inside the `testdata.leveldb` like other tests.
- Use the correct parameters when instantiating the leveldb store on tests
> fix created leveldb dir name

- .github/workflows/integration-test.yml
- .github/workflows/main.yml
- __tests__/integration/hathorwallet_facade.test.js
- src/new/wallet.js
- src/tokens.js
- Add parameter to set new created authority address when minting/melting tokens
- This address by default must belong to the same wallet but another parameter was added to allow external addresses.
- I decided not to add it to the wallet service facade because it's a specific request and it will be added to both facades in the release candidate version
- Added the stable master branch to the github workflow files just to trigger the CI, it will be removed before merging
> feat: add new parameter to set authority address when minting/melting tokens

- __tests__/integration/hathorwallet_facade.test.js
- src/new/wallet.js
- src/tokens.js
- Create token and create NFT methods must have a parameter to set the address to send the authority (mint/melt) output created.
- This feature is a back port, so it was just done in the old facade because it doesn't need support for the wallet service facade for now.
> feat: add new parameter to set authority address for mint/melt when creating a token

- __tests__/storage/leveldb/leveldb_store.test.js
- __tests__/storage/memory_store.test.js
- src/new/wallet.js
- src/storage/leveldb/store.ts
- src/storage/memory_store.ts
- src/storage/storage.ts
- Allow getAccessData to return null when it is not set, methods that require access data to be set should throw `UninitializedWalletError`
> feat: do not throw on getAccessData

- __tests__/integration/hathorwallet_facade.test.js
- __tests__/models/address.test.js
- __tests__/wallet/wallet.test.ts
- src/models/address.ts
- src/new/wallet.js
- src/storage/storage.ts
- src/utils/tokens.ts
- src/wallet/wallet.ts
- `mintTokens` method must have a parameter to set the address to send the new mint authority created
- `meltTokens` method must have a parameter to set the address to send the new melt authority created
> feat: add new parameter to set mint/melt authority address when minting/melting tokens

- .babelrc
- babel.config.js
- package-lock.json
- package.json
- Include the babel plugin `@babel/plugin-transform-async-generator-functions`
- include number balance on the token history reponse of `getTxHistory`
> feat: babel async generator preset

- __tests__/wallet/wallet.test.ts
- src/utils/wallet.ts
- src/wallet/types.ts
- src/wallet/wallet.ts
- Allow starting a wallet-service facade passing the storage as argument
- When starting the wallet-service facade, use the accessData present on the storage if it exists.
> feat: wallet service storage argument

- codecov.yml
@pedroferreira1 merged the coverage from the unit and integration tests, this made the project coverage jump to over 75%.
- Increase project coverage target to 75%
> chore: increase coverage target

- __tests__/integration/hathorwallet_facade.test.js
- __tests__/new/hathorwallet.test.js
- __tests__/utils/crypto.test.ts
- __tests__/wallet/wallet.test.ts
- src/constants.ts
- src/models/network.ts
- src/new/wallet.js
- src/utils/crypto.ts
- src/wallet/api/walletApi.ts
- src/wallet/types.ts
- src/wallet/wallet.ts
- We should have a `signMessageWIthAddress` method on both facades
> feat: sign message

- __tests__/models/transaction.test.js
- src/constants.ts
- src/models/create_token_transaction.ts
- src/models/transaction.ts
- src/models/types.ts
- src/types.ts
- src/utils/helpers.ts
- src/utils/transaction.ts
- src/wallet/types.ts
- Implement new `signalBits` field in all transaction models, occupying the first byte of a transaction
- Change the `version` field in all transaction models, so it only occupies the second byte of a transaction
> feat(feature-activation): implement signal bits

- __tests__/new/hathorwallet.test.js
- __tests__/wallet/wallet.test.ts
- src/new/wallet.js
- src/utils/transaction.ts
- src/wallet/wallet.ts
- add param signTx to prepareTransaction in src/utils/transaction.ts
- add optional attribute to prepareCreateNewToken in src/new/wallet.ts
- add optional attribute to prepareMintTokensData in src/new/wallet.ts
- add optional attribute to prepareMeltTokensData in src/new/wallet.ts
> feat: add signTx param to sign transaction as optional

- package.json
- tsconfig.json
- Use babel to compile lib files
The babel was only building js files which are very few after we refactored the lib to use primarily typescript.
To fix this we will use babel to build all js files then use tsc only to type check and emit type declarations.
This idea and configuration was taken from the typescript documentation ([reference](https://www.typescriptlang.org/docs/handbook/babel-with-typescript.html#babel-for-transpiling-tsc-for-types))
> chore: actually use babel to compile lib

- src/new/wallet.js
- Resolve promise leak in the wallet start method when using the VersionApi
Related to: https://github.com/HathorNetwork/hathor-wallet-mobile/issues/364
> fix: promise leak by capturing rejection from getVersion

- __tests__/integration/atomic_swap.test.js
- __tests__/integration/hathorwallet_facade.test.js
- __tests__/integration/hathorwallet_others.test.js
- __tests__/integration/helpers/genesis-wallet.helper.js
- __tests__/integration/helpers/wallet.helper.js
- __tests__/integration/storage/leveldb.test.js
- __tests__/integration/storage/storage.test.js
- jest-integration.config.js
- src/new/wallet.js
- src/types.ts
- All inject funds calls must wait for the destination wallet to receive the new transaction, besides the genesis.
- Refactor of `waitForTxReceived` integration tests helper method:
- Depending on the ws event to handle the tx received could lead to bugs, since the event might arrive even before the `waitForTxReceived`. This used to be handled with a `getTx` method but this may also cause bugs, since the tx must be added AND processed before considered to fully arrived, so all the metadata is updated.
- Create a new attribute for transactions that arrive from the websocket `processingStatus`, so we know when these transactions have finished processing and its metadata is fully updated.
- When expecting a tx to be received in the websocket, we expect its metadata to be updated. However, …
> tests: start marking utxos as spent when tx is received for integration tests

- __tests__/api/health.test.ts
- __tests__/api/txMining.test.ts
- __tests__/api/version.test.ts
- src/api/health.js
- src/api/txApi.js
- src/api/txMining.js
- src/api/version.js
- src/lib.ts
- Include methods to get health information on tx-mining-service and hathor-core
Note: The health endpoint in hathor-core is still being developed in https://github.com/HathorNetwork/hathor-core/pull/807. When it's released and available on most fullnodes, we will create a new PR to use it in the wallet-lib.
> feat: support health-check endpoints on hathor-core and tx-mining-service

- src/new/wallet.js
This function extracts the pin from options or get the default value from the wallet. However, it causes an error in the wallet-mobile because the wallet doesn't have a default pin.
- Pass the right argument to the `getHDPrivateKeyFromAddress` function.
> fix: call getHDPrivateKeyFromAddress with options as second param

- __tests__/integration/hathorwallet_facade.test.js
- __tests__/utils/tokens.test.js
- src/new/wallet.js
- src/utils/tokens.ts
A use case needs to create tokens with data script outputs (more than one in the same create token transaction, if possible). This is similar to the Create NFT transaction, however we would be marking this token as an NFT in our metadata bucket, which is bad for the use case.
Because of that, we decided to add support to data script outputs in the lib methods adding them in the last positions of outputs, because the NFT standard expects the data output to be in the first output.
This is a short term solution and a new project will be created to define better how to better identify an NFT token, without fixing where the data output must be.
- Add support for one or many data script outputs in a token create transaction.
- This token can't be identified as an NFT by our wallet service …
> feat: add support for multiple data script outputs when creating a token

- __tests__/integration/hathorwallet_facade.test.js
- src/new/wallet.js
Calling `getAddressIndex` with an address that does not belong to the wallet is throwing an error but should return `null`, according to the documentation.
```
/**
* Get index of address
* Returns null if address does not belong to the wallet
*
* @param {string} address Address to get the index
*
* @return {Promise<number | null>}
**/
```
- Return `null` for the `getAddressIndex` method, if the address does not belong to the wallet.
> fix: address index method should return null in case the address does not belong to the wallet

- __tests__/api/health.test.ts
- src/api/health.js
- We should use the actual `/health` endpoint on hathor-core when getting its health. We previously used the `/version` because the health one hadn't been implemented yet.
> chore: use new hathor-core health endpoint

- __tests__/models/transaction.test.js
- __tests__/utils/transaction.test.js
- src/models/transaction.ts
- src/utils/transaction.ts
- Do not reverse the hash of the `dataToSign`
- Stop considering signature message as little endian
> feat: stop reversing dataToSignHash

- __tests__/integration/hathorwallet_facade.test.js
- __tests__/integration/storage/storage.test.js
- __tests__/new/hathorwallet.test.js
- __tests__/storage/storage.test.js
- __tests__/utils/transaction.test.js
- src/new/wallet.js
- src/storage/storage.ts
- src/types.ts
- src/utils/transaction.ts
- src/wallet/partialTxProposal.ts
- Allow the user to override the tx signature method.
- Default to `transactionUtils.signTransaction`, our main signature method.
> chore: storage method to sign tx with custom override

- src/nano_contracts/parser.ts
- Use `getAddressFromPubkey` to parse address in the nano parser class
> refactor: use getAddressFromPubkey to parse address in the nano parser class

- __tests__/integration/nanocontracts/bet.test.js
- __tests__/new/hathorwallet.test.js
- src/new/wallet.js
It causes error when calling getTxHistory in the saga effect to fetch tx history on wallet-mobile.
- Fix `getTxHistory` by passing network object to `getAddressFromPubkey`
> fix: getTxHistory [1]

- .github/workflows/main.yml
Codecov's upload task on CI broke, it used to be unstable so we suspected that was the case but apparently it is now required to use a token.
- Add a secret token to the repo's settings
- Add CI config to expose the token to codecov's upload task
> fix: fix codecov upload with token

- .github/workflows/integration-test.yml
- __tests__/wallet/mineTransaction.test.ts
- src/storage/leveldb/store.ts
- src/wallet/mineTransaction.ts
This PR aims to fix minor bugs on the CI tests before upgrading to NodeJS 20 on #635 :
After upgrading to NodeJS 20, the `mineTransaction.test.ts` unit tests started failing. This was due to a stricter policy by Node of crashing whenever there is an unhandled promise in the application, instead of just emitting a warning as it was on NodeJS 14.
- Promises on `MineTransaction` tests should always be handled
- The CI must be passing for all PRs
> fix: Failing tests on CI

- src/storage/leveldb/store.ts
We were having intermittent failures on the CI ( [example](https://github.com/HathorNetwork/hathor-wallet-lib/actions/runs/9003097793/job/24732955502) ) due to a NanoContract registration promise being out of sync with the flow of the test suite. This PR ensures they stay in sync by returning the lower level promise instead of just firing it.
This is a similar solution as the one applied [on 641](https://github.com/HathorNetwork/hathor-wallet-lib/pull/641/files#diff-f46b617cbedd7301cb4b8766792b1a9ecb39300f645dc17ac13fd3cc9b969c33).
- The `registerNanoContract` method should return its underlying operation `Promise<void>`
> fix: async registerNanoContract call

- package-lock.json
- package.json
- Upgrades `axios` from `0.21.4` to `1.6.8`
Some resources claim that no changes are necessary to update this major version, while others claim entire [migration guides](https://github.com/bmuenzenmeyer/axios-1.0.0-migration-guide) are required. For this repository no changes were necessary.
> chore: Upgrades `axios`

- __tests__/nano_contracts/deserializer.test.js
- __tests__/nano_contracts/serializer.test.js
- src/nano_contracts/deserializer.ts
- src/nano_contracts/serializer.ts
- Add support in the serializer and deserializer class for optional parameter.
- Fix bug in the signed data deserializer, where the bytes value was not being converted to hex.
**Note:** Unfortunately, we currently don't have any blueprints with optional parameters, so we can't test this in the integration tests, thus only unit tests were added.
> feat: add support for optional parameters in nano contract serializer/deserializer

- __tests__/storage/storage.test.js
- src/new/wallet.js
- src/storage/storage.ts
- It should add cleanTokens to new/wallet on `stop` method
> feat: add cleanTokens to new/wallet

- package-lock.json
- package.json
- it should bump wallet-lib version to v1.5.0
> bump: v1.5.0

- __tests__/storage/storage.test.js
- src/storage/leveldb/nanocontract_index.ts
- src/storage/leveldb/store.ts
- src/storage/memory_store.ts
- src/storage/storage.ts
- src/types.ts
- Add method to iterate through registered nano contracts on storage and in both implemented stores (memory and leveldb).
- Add `address` to `INcData`.
> feat: add method to iterate over all registered nano contracts on storage

- package-lock.json
- package.json
- Upgrades `ws` from `7.5.9` to `8.17.0`
There is a list of breaking changes on [v8's release notes](https://github.com/websockets/ws/releases/tag/8.0.0), most notably the deprecation of NodeJS < 10 and changes to the lib's error handling methods.
To validate for these changes, besides this repository unit and integration tests, the built version was tested manually on the Desktop Wallet and passed the full automated test suite for the Headless Wallet.
> chore: Upgrades `ws`

- __tests__/storage/leveldb/leveldb_store.test.js
- __tests__/storage/memory_store.test.js
- __tests__/storage/storage.test.js
- src/storage/leveldb/nanocontract_index.ts
- src/storage/leveldb/store.ts
- src/storage/memory_store.ts
- src/storage/storage.ts
- src/types.ts
- Add methods in storages and default stores to update the address associated with a registered nano contract.
- Add `getRegisteredNanoContracts` to the `IStorage`.
> feat: add methods to update nano contract address in storage and store

- package-lock.json
- package.json
- Upgrades `mock-socket` from `8.1.1` to `9.3.1`
The [changelogs](https://github.com/thoov/mock-socket/blob/master/CHANGELOG.md) only offer data about version 9. The [v9 release](https://github.com/thoov/mock-socket/releases/tag/9.0.0) itself only mentions a deprecation of NodeJs older than 12, so there are probably no breaking changes here.
> chore: upgrades `mock-socket`

- src/nano_contracts/utils.ts
- src/new/wallet.js
The desktop wallet has a flow for sending tx that it expects the `SendTransaction` object because internally we handle the states of mine/push with the error handling and UI feedback for the user.
- Transform the create and send nano contract method into two, (i) build tx and create `SendTransaction` object and (ii) create, mine, and push.
> refactor: split nano contract send method into create and mine/push

- .github/workflows/integration-test.yml
- .github/workflows/main.yml
- Upgrades the workflow actions to use NodeJS 20
It is expected that the upgrade for CodeCov action avoids an issue we're currently having of the codecov results not being uploaded correctly within this workflow. ( [Diff between the two minors](https://github.com/codecov/codecov-action/compare/v4.3.0...v4.5.0) we're upgrading )
> chore: Upgrades workflow actions

- package-lock.json
- package.json
The `abstract-level` dependency is used directly by six classes in `Storage -> LevelDB` file. To avoid this linting error, we should explicitly declare it in the `package.json` file
- Fixes [no-extraneous-dependencies](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-extraneous-dependencies.md) rule
> fix: no-extraneous-dependencies rule

- __tests__/utils/storage.test.js
- src/utils/storage.ts
The linting made on https://github.com/HathorNetwork/hathor-wallet-lib/pull/682 accused that a single line inside the `utils/storage.ts` was not being tested and this broke the CI in the PR.
Upon investigation, this proved to be an actual bug on the `updateTokensData` method that would require a full test suite and changes to the utils to fix it.
The impact of this bug on applications running prior to NodeJS 16 was to exhibit a warning indicating that an _Unhandled Exception_ happened whenever the `[GET] 'thin_wallet/token'` fullnode endpoint failed. Starting with NodeJS 16 this started throwing an unhandled error that may crash applications that do not handle this properly [at the global level](https://nodejs.org/api/process.html#event-unhandledrejection).
- Fixes the `updateTokensData` …
> fix: updateTokensData retry mechanism

- .eslintrc.js
- .github/workflows/main.yml
- __tests__/integration/hathorwallet_others.test.js
- __tests__/storage/storage.test.js
- package.json
- src/models/partial_tx.ts
- src/nano_contracts/builder.ts
- src/storage/storage.ts
- src/utils/numbers.ts
- src/utils/storage.ts
- src/utils/transaction.ts
- Linting of the `src` folder ( the `tests` folder will be implemented later )
- Formatting of the entire application with `prettier`
- Automatic formatting debt after #670 
- Explicit declaration of important eslint rules that will be left for later
This PR is separated into three commits for easier review in separate contexts: one for the workflow itself, other for the formatting technical debt and other for the rules that will be left for later
> feat: Add linting and formatting to CI

- .github/workflows/release-sync.yml
We sometimes forgot to merge the contents of the `release` branch back into `master` after a successful release. This workflow aims to automate the creation of the PR for this.
There is no simple command on the GitHub CLI to add a card to a specific column. To do this it's necessary to execute mutation queries directly to GitHub API, with `write` permissions for the entire project, which raise a flag about the width of the necessary permissions.
The available actions that could execute this are still in beta, or were made obsolete by the GitHub Projects v2. So it was decided to implement the queries and mutation directly inside the workflow.
To facilitate the use of this functionality in other repositories, we should implement a GitHub Action inside the HathorNetwork organization with …
> feat: Workflow to sync release into master

- __tests__/integration/helpers/genesis-wallet.helper.ts
- __tests__/integration/helpers/wallet.helper.ts
- src/constants.ts
- src/models/output.ts
- src/models/partial_tx.ts
- src/models/transaction.ts
- src/models/types.ts
- src/nano_contracts/types.ts
- src/new/sendTransaction.ts
- src/new/wallet.js
- src/storage/storage.ts
- src/types.ts
- src/utils/buffer.ts
- src/utils/tokens.ts
- src/utils/transaction.ts
- src/utils/utxo.ts
- src/wallet/partialTxProposal.ts
- src/wallet/types.ts
- src/wallet/wallet.ts
Depends on https://github.com/HathorNetwork/hathor-wallet-lib/pull/730
See https://github.com/HathorNetwork/internal-issues/issues/363.
To add support for greater output values, the output value type must be changed from `number` to `bigint`. In preparation for that, this PR performs an extremely simple refactor by introducing a type alias `type OutputValueType: number`, and changing all related places to use it. Then, we can change the type alias to `bigint`, reducing the size of the final conversion PR.
- All instances of variables/parameters such as `value`, `authorities`, `balance`, and `amount` that are related/come from an output value are changed from type `number` to `OutputValueType`.
- No behavior should change.
> refactor: create OutputValueType

- __tests__/integration/configuration/docker-compose.yml
- __tests__/integration/nanocontracts/bet.test.ts
- __tests__/nano_contracts/deserializer.test.ts
- src/nano_contracts/builder.ts
- src/nano_contracts/deserializer.ts
- src/nano_contracts/parser.ts
- src/nano_contracts/serializer.ts
- src/nano_contracts/types.ts
- src/nano_contracts/utils.ts
There are nano contract method arguments and attributes that have specific types and we can improve user usability of the clients when considering them. For example, an address is decoded in bytes but if we know that the argument is an address we can validate it better and expect in the clients a base58 string instead of a hexadecimal of the decoded address.
In this PR we will consider the new types as following:
bytes: `TxOutputScript`, `TokenUid`, `VertexId`, and `Address`
int: `Timestamp` and `Amount`
Even though there are no differences when serializing/deserializing a Timestamp/Amount from a normal integer, we can use this information to create the UI in a way that is more user friendly.
- Consider new custom types when serializing/deserializing data for nano contract.
- Accept …
> feat: handle nano custom types in the parser and builder classes

- .github/workflows/integration-test.yml
- Upgrade upload-artifact to v4 which uses node20
> chore: upgrade upload-artifact to v4

- src/api/nano.ts
When I was creating a new API in the hathor core to get the blueprint source code, I had a discussion with @msbrogli about the best path for it. We ended up deciding to use `/blueprint/source` and, to keep consistency, we changed `/blueprint` (which returned the blueprint information) to `/blueprint/info`.
We decided to do it now that we don't have many clients using it and we can quickly update the lib and wallets with this new version. 
- Update blueprint information endpoint URL from hathor core
> feat: update nano hathor core URL for blueprint info endpoint

- __tests__/nano_contracts/deserializer.test.ts
- src/nano_contracts/deserializer.ts
- src/nano_contracts/serializer.ts
- src/nano_contracts/utils.ts
- Add new nano contract type `ContractId` as `bytes` in the Serializer and Deserializer
- Add tests for all contract types that are handled as bytes.
> feat: add new nano contract type contractId

- src/new/connection.ts
- src/storage/leveldb/store.ts
- src/storage/memory_store.ts
- src/storage/storage.ts
- src/sync/stream.ts
- src/types.ts
- Move the history sorting to before the processing
It was tested loading a wallet with almost 400k transactions, the load time went from 40 minutes using the normal stream to 1 and a half minute.
This is because this change is only really impactful on wallets with over 20k transactions where each sorting becomes slow enough to impact the sync prrocess.
- Fix Websocket logger argument being undefined.
- When logging an unknown stream message, show the contents
> feat: move the history sort to the pre-process method

- package-lock.json
- package.json
- src/errors.ts
- src/new/wallet.js
- src/sync/gll.ts
- Create a global load lock (GLL).
- GLL should only allow 5 wallets to load concurrently at any time.
- Any wallets trying to sync the history should wait on the GLL for their turn.
- Log time wallets waited on GLL to start syncing.
The GLL is an instance of a promise queue, meaning it runs the tasks on queue but only allow a number of concurrent runs.
For instance 5 concurrent tasks, meaning only 5 wallets can load at any given time.
The `syncHistory` method of the wallet now just uses the `addTask` to enqueue the actual history sync
```js
async syncHistory(startIndex, count, shouldProcessHistory = false) {
if (!(await getSupportedSyncMode(this.storage)).includes(this.historySyncMode)) {
throw new Error('Trying to use an unsupported sync method for this wallet.');
}
const syncMethod = …
```
> feat: global load lock

- src/sync/gll.ts
- Create an event emitter that emits an event with the taskId as a name to avoid multiple listeners on the same event name
- Use once so listeners are cleaned automa
> Change listener to be used only once

- src/sync/stream.ts
https://github.com/HathorNetwork/hathor-core/pull/1129
- Send end stream ACK
> feat: send end ACK

- src/new/wallet.js
- Fix promise leak in call of getTokenDetails
>[!NOTE]
>We have had a similar problem before, see https://github.com/HathorNetwork/hathor-wallet-lib/pull/584.
> fix: promise leak

- __tests__/stream.test.ts
- package-lock.json
- package.json
- src/new/connection.ts
- src/new/wallet.js
- src/sync/stream.ts
- During history stream queue processing, await the end of JS tasks execution at the end of each loop
- This will make IO tasks and other tasks free to run so the queue processing does not block the main loop.
- If a sync is aborted while it waits for execution, we should abort as soon as possible to avoid executing needlessly.
- Save the capabilities set from the fullnode and check if the fullnode is history-streaming capable.
> feat: treat streaming edge cases

- __tests__/storage/storage.test.ts
- src/storage/storage.ts
- Fix the setTimeout of the `selected_as_input` ttl to actually undo the change.
> fix: selected_as_input ttl

- .github/workflows/lint.yml
- .github/workflows/unit-test.yml
- Split unit tests and linter CI workflows
> chore: split test and linter CI

- __tests__/new/wallet-utxo.test.ts
- src/new/wallet.js
- src/utils/transaction.ts
- Create new methods that build transactions but return the `SendTransaction` instance instead of automatically mining the transactions.
> feat: new methods that return SendTransaction

- __tests__/integration/hathorwallet_facade.test.ts
- __tests__/new/hathorwallet.test.ts
- src/types.ts
- src/utils/tokens.ts
- src/utils/utxo.ts
When we try to mint or melt tokens with more than the available amount, it throws an error. The error message informs the requested amount to mint or melt and the **available** token amount. The bug here is that the available amount is always zero.
- The available amount should be equal to the total available token, not zero
It closes https://github.com/HathorNetwork/internal-issues/issues/398
> fix: error message for over available tokens to mint or melt

- __tests__/integration/hathorwallet_facade.test.ts
- __tests__/new/hathorwallet.test.ts
- src/types.ts
- src/utils/tokens.ts
- src/utils/utxo.ts
Start the release process for version `1.14.1`.
> release: v1.14.1

- __tests__/models/output.test.ts
- __tests__/utils/bigint.test.js.ts
- __tests__/utils/buffer.test.ts
- package-lock.json
- package.json
- src/api/schemas/txApi.ts
- src/api/schemas/wallet.ts
- src/api/txApi.ts
- src/api/wallet.ts
- src/models/output.ts
- src/new/wallet.js
- src/schemas.ts
- src/storage/leveldb/address_index.ts
- src/storage/leveldb/history_index.ts
- src/storage/leveldb/token_index.ts
- src/storage/leveldb/utxo_index.ts
- src/types.ts
- src/utils/bigint.ts
- src/utils/buffer.ts
- src/utils/storage.ts
- src/websocket/index.ts
- tsconfig.json
Depends on https://github.com/HathorNetwork/hathor-wallet-lib/pull/797
See https://github.com/HathorNetwork/internal-issues/issues/363.
This PR adds the necessary structures to support bigint fields, however it does _not_ yet change the `OutputValueType` to `bigint`.
- Implement `bigIntToBytes()` and remove `signedIntToBytes()` support for 8 bytes.
- Implement `unpackToBigInt()` and remove `unpackToInt()` support for 8 bytes.
- Update `bytesToOutputValue()` to use `unpackToBigInt()`.
- Dependencies:
- Added `zod`.
- `level-transcoder` was added explicitly but was already an indirect dependency.
- Removed `long`.
- Create `api/txApi` and `api/wallet` Zod schemas, updating requests to use `transformJsonBigIntResponse()`.
- Update `Output.valueToBytes()` to use `bigIntToBytes()` instead of …
> feat: implement bigint support

- .github/workflows/integration-test.yml
- .github/workflows/lint.yml
- .github/workflows/unit-test.yml
- __tests__/utils/bigint.test.js.ts
- package.json
- src/utils/bigint.ts
Depends on https://github.com/HathorNetwork/hathor-wallet-lib/pull/728
- Remove support for Node v20.
> chore: remove support for Node v20

- __tests__/utils/bigint.test.js.ts
- src/utils/bigint.ts
During manual testing with the updated wallet-headless, I found a bug in the logic used to revive BigInts. We should check using JS `Number.MAX_SAFE_INTEGER`, instead.
- Make `bigIntReviver()` a standalone function in the `JSONBigInt` object.
- Fix logic `bigIntReviver()` uses to determine when it should return a `BigInt`.
- Add more tests.
> fix: bigint reviver

- __tests__/integration/nanocontracts/bet.test.ts
- src/new/wallet.js
- src/storage/leveldb/store.ts
- src/storage/leveldb/utxo_index.ts
- src/storage/memory_store.ts
- src/storage/storage.ts
- src/sync/utils.ts
- src/types.ts
- src/utils/storage.ts
Nowadays we run the method to process the wallet full history every time a new tx arrives in the ws. Wallets with many transactions/addresses usually take a long time (0.5s) to process their entire history. There are cases where the wallet returns and error because of insufficient funds because it's processing the history of a recent transaction that has just arrived when the user wants to send a new tx.
- Process only the single tx that arrives in the ws (including delete the utxos that are being spent in this tx).
- If this tx is an update and the voided state has changed, then we run the full process history, just to make this easier.
- While this processing is being done we change the wallet state to PROCESSING, so users know that they must wait until creating the next tx.
> feat: process txs as they arrive

- __tests__/integration/hathorwallet_others.test.ts
- __tests__/integration/helpers/genesis-wallet.helper.ts
- __tests__/integration/helpers/wallet.helper.ts
- Check that when a metadata update event is received the history is processed correctly.
> tests: check tx processing on metadata updates

- __tests__/new/hathorwallet.test.ts
- src/new/wallet.js
`selectUtxos` util in `src/utils/transaction.ts` requires the utxo array to be sorted for the selection to be optimal.
The `getUtxosForAmount` method of the wallet facade was not following this and in some cases the utxos chosen by this method were not the best selection possible, maybe even failing some transactions due to going over the input limit.
To fix this we need to get the sorted utxo list.
- on `getUtxosForAmount` use the option to retrieve utxos sorted by amount.
- test a case where utxo selection would choose a list of utxos instead of a single utxo that could meet the requirements.
> fix: utxo selection for getUtxosForAmount

- __tests__/integration/configuration/docker-compose.yml
The next full node version will not support memory storage anymore and one of the nano contract indexes already doesn't support it. The main problem with using rocksdb is that the full node service takes more time to become healthy (with status port ready to receive requests), so the tx mining service and the test itself were breaking. 
Then I created a healthcheck to validate if the node is already receiving http requests. I tried using `curl` or `wget` but the docker container doesn't have them installed, that's why it's using a python script to validate.
- Use rocksdb in the fullnode that runs in the integration tests
> tests: use rocksdb in the integration tests

- __tests__/integration/hathorwallet_facade.test.ts
- src/api/schemas/txApi.ts
We recently added a zod schema validation to the lib code and, even though we use as output type 'P2SH' in the lib (as we have in our types), the full node uses 'MultiSig'. We didn't notice that and every time we were requesting the `/transaction` API of a tx with a P2SH output, an error was being thrown.
- p2sh output type comes as MultiSig from hathor core
> fix: p2sh output type comes as MultiSig from hathor core

- __tests__/integration/nanocontracts/bet.test.ts
The test wants to wait until the nano contract tx has its method executed and I was using `waitNextBlock`. This method was causing some intermittent errors because it's an async call. The best way to guarantee that the nano method will have already been executed is to use `waitTxConfirmed`, then the tx will have a `first_block`.
- Use `waitTxConfirmed` to guarantee a tx has first block.
> tests: improve how we wait for a tx to be confirmed

- __tests__/wallet/walletSchemas.test.ts
- src/wallet/api/schemas/walletApi.ts
- Update `txByIdResponseSchema` to make the `height` field optional and nullable (as it makes sense since a transaction might not be confirmed yet)
- Modify tests in `__tests__/wallet/walletSchemas.test.ts` for `txByIdResponseSchema` to reflect the changes
> tests: improved tests with more test cases for height in txById

- __tests__/integration/hathorwallet_facade.test.ts
- __tests__/integration/nanocontracts/bet.test.ts
- src/nano_contracts/builder.ts
- src/nano_contracts/types.ts
- src/new/wallet.js
- src/utils/tokens.ts
- Add method in the wallet facade to create a Create Token Transaction with nano header.
- Add new flag to the mint/create token utils methods to skip deposit fee management (so the contract can handle it)
- Refactor NanoContractBuilder build method in different methods (verify, serializeArgs, buildInputsOutputs, buildTransaction)
- Add support in NanoContractBuilder to create a Transaction or CreateTokenTransaction with nano header and with possibility for the contract's withdrawal action to pay for the token creation deposit fee.
> feat: add support for creating a create token transaction with nano header

- .github/workflows/integration-test.yml
- .github/workflows/lint.yml
- .github/workflows/unit-test.yml
- __tests__/integration/configuration/docker-compose.yml
- __tests__/integration/nanocontracts/bet.test.ts
- __tests__/nano_contracts/deserializer.test.ts
- __tests__/nano_contracts/methodArg.test.ts
- __tests__/nano_contracts/serializer.test.ts
- setupTests-integration.js
- src/models/address.ts
- src/nano_contracts/builder.ts
- src/nano_contracts/deserializer.ts
- src/nano_contracts/methodArg.ts
- src/nano_contracts/parser.ts
- src/nano_contracts/serializer.ts
- src/nano_contracts/types.ts
- src/nano_contracts/utils.ts
The new `SignedData` is meant to improve protection, the data should be `<signature, value, type>`.
In the original `SignedData` (now called `RawSignedData`) the oracle signs the value (serialized as the type) to generate the signature.
For the new `SignedData` the oracle signs the tuple `[ncId, value]` serialized as  `Tuple[ContractId, type]` to generate the signature.
`ncId` is the nano contract id being invoked.
The idea is to avoid replay attacks where we get the signed value from one contract to use on another contract.
The serialization itself  does not change since the `ncId` is not part of the data sent, it is only used when generating the signature and when validating it.
There is a distinction from:
- "user inputs" meant to be used as nano contract arguments
- Serialized …
> feat: new SignedData and method argument parser

- __tests__/integration/nanocontracts/authority.test.ts
- src/nano_contracts/builder.ts
- src/utils/tokens.ts
There were two bugs:
(i) the utxo selection for deposit action and token creation deposit fee happens in different phases, so we must mark the utxos as selected after the first phase, so we don't select the same one in the second phase.
(ii) we were selecting two different utxos when we could have only one for an HTR deposit action and token creation deposit fee.
- Mark utxos selected in actions as used.
- When selecting an HTR utxo for deposit action, it already selects also for the token creation deposit, if there are any creation.
Note: I decided to change the logic a bit for the `contractPaysForTokenDeposit` flag. Now it will pay for any data output fee in the token creation as well. The nano contract method code will validate any logic like this.
> fix: use single utxo selection for deposit action and token deposit fee

- __tests__/nano_contracts/deserializer.test.ts
- __tests__/nano_contracts/methodArg.test.ts
- __tests__/nano_contracts/serializer.test.ts
- src/nano_contracts/deserializer.ts
- src/nano_contracts/methodArg.ts
- src/nano_contracts/serializer.ts
- src/nano_contracts/types.ts
- Change `ContractId`, `BlueprintId`, `VertexId` and `Address` to use a fixed size bytes serialization where the length is not on the serialized value.
- Change `TokenUid` to use a custom serialization.
- Change `Amount` to use leb128 unsigned serialization
- Change `int` to use leb128 signed serialization
- Remove `VarInt` nano contract type
> chore: fixed size bytes serialization

- __tests__/integration/configuration/authority.py
- __tests__/integration/configuration/bet.py
- __tests__/integration/configuration/docker-compose.yml
- __tests__/integration/nanocontracts/authority.test.ts
- __tests__/integration/nanocontracts/bet.test.ts
- __tests__/utils/transaction.test.ts
- src/constants.ts
- src/nano_contracts/builder.ts
- src/nano_contracts/header.ts
- src/nano_contracts/types.ts
- src/nano_contracts/utils.ts
- src/new/wallet.js
- src/schemas.ts
- src/storage/storage.ts
- src/types.ts
- src/utils/storage.ts
The latest nano core version had some breaking changes with nano integration that are fixed in this PR.
The most important is the `seqnum` in the nano header class, which is a sequential number for each nano transaction that is signed by the same caller, i.e., the seqnum increases when the same address is used as caller for a nano transaction.
This number should also increase if the nano execution fails and the tx becomes voided because it was confirmed by a block.
- Action name was changed from `Invoke Authority` to `Acquire Authority`.
- Authority action types str was updated to lower case (previously on `deposit` and `withdrawal` were in lower case).
- Blueprint sdk removed support for `is_action_type` method.
- Token info API now considers amount minted by contracts for the total …
> feat: update nano contract integration with new hathor core version

- __tests__/integration/configuration/authority.py
- __tests__/integration/nanocontracts/authority.test.ts
- src/nano_contracts/builder.ts
- Add support for having multiple actions for the same token.
Note: the core code currently doesn't support all possibilities, e.g., DEPOSIT + WITHDRAWAL is not allowed, but in the future it might be. Then I decided not to have any restrictions in the builder, allowing the user to build anything they want regarding actions and the core will validate it. With this, we will already have support if the core changes in the future.
> feat: allow multiple actions per token in nano header

- __tests__/utils/wallet.test.ts
- __tests__/wallet/wallet.test.ts
- src/utils/wallet.ts
- src/wallet/wallet.ts
- Add `getNetwork` method in the wallet service facade, that was missing from the old facade.
- Create util method to get xpriv from private key data.
> feat: add xpriv util method and getNetwork in wallet service facade

- __tests__/integration/nanocontracts/bet.test.ts
- src/storage/memory_store.ts
- src/storage/storage.ts
- src/types.ts
- src/utils/storage.ts
When we receive a new tx and it's voided, we run a full history processing, clearing everything in the storage. If we were to create a new nano tx in the meanwhile, we would be getting an outdated seqnum. 
The seqnum data is not affected by voided txs (in our integration), so I decided to move this to a different metadata, which is not emptied on this full history processing.
- Move seqnum storage to a different metadata map, so it doesn't get emptied on metadata clear
> fix: seqnum storage should be in a separate metadata map

- __tests__/wallet/wallet.test.ts
- src/nano_contracts/builder.ts
- src/utils/transaction.ts
- src/wallet/api/schemas/walletApi.ts
- src/wallet/api/walletApi.ts
- src/wallet/sendTransactionWalletService.ts
- src/wallet/types.ts
- src/wallet/wallet.ts
- src/wallet/walletServiceStorageProxy.ts
- Update schemas for the proxy methods with nano contract responses
- Added missing `createAndSendNanoContractCreateTokenTransaction` method
- Created a `storage` proxy, to override util methods so they're compatible the the wallet-service
> refactor: send nano contract tx working on the wallet-service

- src/wallet/sendTransactionWalletService.ts
- Pin from method argument must have precedence over object pin
> fix: pin from arg must have precedence over object pin

- __tests__/integration/configuration/docker-compose.yml
- __tests__/integration/hathorwallet_others.test.ts
- src/schemas.ts
- src/types.ts
- src/wallet/api/schemas/walletApi.ts
- src/wallet/types.ts
- Make timestamp of `nc_context` optional in the types and schemas
- Update docker image for integration tests to use the master latest commit
> fix: timestamp in nano nc_context is now optional

- src/wallet/wallet.ts
The walletApi method to request a new auth token ignores the wallet-id from the arguments and uses the `instance.walletId` which is not set during the initial request for an auth token.
This would make the first calls to the auth token api fail even if the request was valid.
- We should set the walletId before calling the auth token api
> fix: set walletid before token renew

- .github/workflows/integration-test.yml
- __tests__/integration/configuration/docker-compose.yml
- __tests__/integration/walletservice_facade.test.ts
- We should have the infrastructure in place to test the Wallet Service facade
- We should have one green test in the suite: a `200` response from the `/version` endpoint
> [!NOTE]
> The Wallet Service repository has only recently implemented the Docker images, a feature needed by this PR.
> This was done by https://github.com/HathorNetwork/hathor-wallet-service/pull/283 .
To avoid unnecessary block validation delays in this early stage of development, comment out the [block waiting commands](https://github.com/HathorNetwork/hathor-wallet-lib/blob/cdd6620a9df605f0d474c2afc52f0392916ca0f4/setupTests-integration.js#L58-L71)  in the setup tests and run the tests only in the new file by using the `SPECIFIC_INTEGRATION_TEST_FILE=walletservice_facade` environment variable.
> test: Wallet Service infrastructure
