- __tests__/transaction_utils.test.js
- src/transaction.js
- src/wallet.js
> fix: outputs sum should ignore authority outputs

- src/api/wallet.js
- src/constants.js
- src/helpers.js
- Considering merged mined block version when checking if is block;
- Adding method to get data from tokens list API.
> Small changes to support new UI for explorer using new APIs

- src/WebSocketHandler.js
- src/api/wallet.js
- src/version.js
- src/wallet.js
> feat: handling block reward lock in inputs choosing and balance

- __tests__/transaction_utils.test.js
- src/constants.js
- src/errors.js
- src/transaction.js
- src/version.js
- src/wallet.js
> feat: adding validation of max number of inputs and outputs of a tx

- index.js
- src/new/README.md
- src/new/wallet.js
Still want to find a better place and name to use for this "new version" of the lib
> refactor: headless incorporation

- __tests__/wallet.test.js
- __tests__/wallet_utils.test.js
- package-lock.json
- src/errors.js
- src/transaction.js
- src/wallet.js
> feat: adding new methods for hardware wallet

- src/api/wallet.js
- src/transaction.js
- Add method to call API of address balance;
- Add method to check if address is valid
> feat: search address

- src/wallet.js
> feat: updating txs count while paginating address history request

- src/constants.js
- src/transaction.js
> feat: improving send tokens timeout message

- __tests__/tokens_utils.js
- index.js
- src/api/axiosWrapper.js
- src/api/txMining.js
- src/api/txMiningAxios.js
- src/constants.js
- src/helpers.js
- src/new/sendTransaction.js
- src/new/wallet.js
- src/tokens.js
- src/transaction.js
It's still a draft because there are some things to be done:
> feat: using tx mining API to send transactions

- __tests__/utils/wallet.test.js
Tests to check if:
- bitcore behavior on HDPrivateKey derivation has changed
- Our wallet address generation from seeds hasn't changed.
> test: hdprivkey derivation

- __tests__/transaction_utils.test.js
- src/models/script_data.ts
- src/new/wallet.js
- src/tokens.js
- src/transaction.js
- src/utils/helpers.ts
- src/wallet/types.ts
- src/wallet/wallet.ts
- HathorWallet facade for full node must have an easy method to create NFTs.
> feat: add support for nft creation on fullnode wallet facade

- src/constants.js
- src/wallet/api/walletApi.ts
- src/wallet/api/walletServiceAxios.ts
- src/wallet/wallet.ts
The app must connect to the testnet wallet service instance when the network is `testnet`
> refactor: passing network and deciding what url to use on wallet-service

- index.js
- src/api/explorerServiceAxios.ts
- src/api/metadataApi.ts
- src/constants.js
- src/new/wallet.js
- We must have methods to load token metadata from explorer service (working for testnet or mainnet)
> feat: fetch wallet tokens metadata on load wallet (old facade)

- package-lock.json
- package.json
> bump: v0.27.0

- package-lock.json
- package.json
- src/models/network.ts
- feat: allow private networks (#286)
> Release v0.27.0

- __tests__/wallet.test.js
- src/wallet.js
- Added a method to change the password
- It should also change everything that is encrypted on storage
- We should also store its hash on storage
> feat: change password

- README.md
- __tests__/wallet.test.js
- package-lock.json
- package.json
- src/wallet.js
> Release v0.28.0

- __tests__/models/output.test.js
- __tests__/models/script_data.test.js
- index.js
- src/utils/scripts.ts
- We must have a method to parse an output script that is a script data.
> feat: create parse script data method

- __tests__/wallet.test.js
- src/wallet.js
- There must be a method that updates the pin and password simultaneously so we can guarantee that they will be updated (or fail) at the same time
> feat: added a changePinAndPassword method

- package-lock.json
- package.json
- Version should have been bumped to v0.29.0
> chore: bumped version to v0.29.0

- __tests__/models/script_data.test.js
- __tests__/wallet.test.js
- index.js
- package-lock.json
- package.json
- src/utils/scripts.ts
- src/wallet.js
> Release v0.29.0

- package-lock.json
- package.json
> chore: bumped version to v0.30.0

- .editorconfig
- __tests__/wallet/api/walletServiceAxios.test.ts
- __tests__/wallet/wallet.test.ts
- index.js
- package-lock.json
- package.json
- src/config.ts
- src/connection.ts
- src/errors.js
- src/new/connection.ts
- src/new/wallet.js
- src/wallet/api/walletServiceAxios.ts
- src/wallet/connection.ts
- src/wallet/types.ts
- src/wallet/wallet.ts
- src/wallet/websocket.ts
- src/websocket/base.ts
- src/websocket/index.ts
> Release v0.30.0

- package-lock.json
- package.json
- src/new/sendTransaction.js
Release for version v0.30.1
- Changes to use ´sendTransaction´ with Ledger.
> Release v0.30.1

- package-lock.json
- package.json
> chore: bump to v0.31.0

- __tests__/wallet/api/walletServiceAxios.test.ts
- __tests__/wallet/wallet.test.ts
- package-lock.json
- package.json
- src/constants.js
- src/utils/wallet.ts
- src/wallet.js
- src/wallet/api/walletApi.ts
- src/wallet/sendTransactionWalletService.ts
- src/wallet/types.ts
- src/wallet/wallet.ts
> Release v0.31.0

- package-lock.json
- package.json
> chore: bump to v0.32.0

- package-lock.json
- package.json
- src/connection.ts
- src/new/connection.ts
- src/wallet.js
- src/wallet/connection.ts
- src/wallet/types.ts
- src/wallet/wallet.ts
> Release v0.32.0

- package-lock.json
- package.json
- src/connection.ts
- src/new/connection.ts
- src/wallet.js
- src/wallet/connection.ts
- src/wallet/types.ts
- src/wallet/wallet.ts
> chore: ci test

- package-lock.json
- package.json
> chore: bump to v0.32.1

- package-lock.json
- package.json
- src/new/wallet.js
- src/wallet/types.ts
- src/wallet/wallet.ts
> Release v0.32.1

- __tests__/models/address.test.js
- __tests__/models/network.test.js
- __tests__/models/p2pkh.test.js
- __tests__/models/p2sh.test.js
- __tests__/models/p2sh_signature.test.js
- __tests__/new_wallet.test.js
- __tests__/transaction_utils.test.js
- __tests__/utils/helpers.test.js
- __tests__/utils/scripts.test.js
- __tests__/utils/wallet.test.js
- __tests__/wallet.test.js
- index.js
- src/constants.js
- src/models/address.ts
- src/models/network.ts
- src/models/output.ts
- src/models/p2pkh.ts
- src/models/p2sh.ts
- src/models/p2sh_signature.ts
- src/models/script_data.ts
- src/new/sendTransaction.js
- src/new/wallet.js
- src/opcodes.js
- src/transaction.js
- src/utils/helpers.ts
- src/utils/scripts.ts
- src/utils/wallet.ts
- src/wallet.js
- Create models for p2sh and p2sh signature
- Add support for p2sh in `createTxFromData`
- Adapt `HathorWallet` constructor to allow receiving multisig configuration
- Save multisig data on storage when starting wallet
- Method to get public key
- Method to get all signatures from partial transaction
- Create `isMultisigWallet` in `src/wallet.js`
- Create `generateAddress` in `src/wallet.js` (refactor where needed to use this method)
> feat: multisig support

- package-lock.json
- package.json
> chore: bump to v0.33.0

- __tests__/models/address.test.js
- __tests__/models/network.test.js
- __tests__/models/p2pkh.test.js
- __tests__/models/p2sh.test.js
- __tests__/models/p2sh_signature.test.js
- __tests__/new_wallet.test.js
- __tests__/transaction_utils.test.js
- __tests__/utils/helpers.test.js
- __tests__/utils/scripts.test.js
- __tests__/utils/wallet.test.js
- __tests__/wallet.test.js
- index.js
- package-lock.json
- package.json
- src/constants.js
- src/models/address.ts
- src/models/network.ts
- src/models/output.ts
- src/models/p2sh.ts
- src/models/p2sh_signature.ts
- src/models/script_data.ts
- src/new/sendTransaction.js
- src/new/wallet.js
- src/opcodes.js
- src/transaction.js
- src/utils/helpers.ts
- src/utils/scripts.ts
- src/utils/wallet.ts
- src/wallet.js
> Release v0.33.0

- package-lock.json
- package.json
> chore: bump lib version to v0.33.1

- package-lock.json
- package.json
> Release v0.33.1

- package-lock.json
- package.json
- https://github.com/HathorNetwork/hathor-wallet-lib/pull/343
- https://github.com/HathorNetwork/hathor-wallet-lib/pull/337
> bump: v0.34.0

- __tests__/wallet/mineTransaction.test.ts
- package-lock.json
- package.json
- src/api/axiosWrapper.ts
- src/api/txMining.js
- src/api/txMiningAxios.ts
- src/config.ts
- src/new/sendTransaction.js
- src/wallet/mineTransaction.ts
- https://github.com/HathorNetwork/hathor-wallet-lib/pull/337
- https://github.com/HathorNetwork/hathor-wallet-lib/pull/343
> Release v0.34.0

- src/new/wallet.js
https://github.com/HathorNetwork/hathor-wallet-headless/issues/153
> fix(mint and melt): mint melt error message

- __tests__/wallet.test.js
- __tests__/wallet/wallet.test.ts
- src/wallet.js
- src/wallet/wallet.ts
This PR solves https://github.com/HathorNetwork/hathor-wallet-lib/issues/351
It also contains a fix for the `changePin` method
- We should have a test for the `executeGenerateWallet` method
- We should have a test for the `generateCreateWalletAuthData` method
- We should have a test for the  `getAcctPathXprivKey` method
- We should have a test to make sure that changing the pin will update the `acctPathXprivkey` correctly on storage
> tests: tests for new wallet service facade methods

- package-lock.json
- package.json
> chore: bump v0.35.0

- package-lock.json
- package.json
- Bumps to version v0.36.0, related to address pre-calculation
> chore/bump v0.36.0

- src/config.ts
- src/connection.ts
- src/network.js
- src/new/wallet.js
- src/wallet/api/walletApi.ts
- src/wallet/connection.ts
- src/wallet/types.ts
- src/wallet/wallet.ts
- src/websocket/base.ts
- We should have methods on both facades to download version data
- We should be able to change network, base server URL and WebSocket server URL using facade methods
- This PR should fix a bug on the websocket connection that would make the class retry the connection forever even if the instance was destroyed
> feat: version data api and changeServer and changeNetwork methods

- package-lock.json
- package.json
> chore: bump lib version to v0.37.0

- __tests__/utils/helpers.test.js
- __tests__/utils/wallet.test.js
- package-lock.json
- package.json
- src/config.ts
- src/connection.ts
- src/network.js
- src/new/sendTransaction.js
- src/new/wallet.js
- src/utils/helpers.ts
- src/wallet/api/walletApi.ts
- src/wallet/connection.ts
- src/wallet/sendTransactionWalletService.ts
- src/wallet/types.ts
- src/wallet/wallet.ts
- src/websocket/base.ts
> Release v0.37.0

- package-lock.json
- package.json
> chore: bump to v0.38.0

- src/new/wallet.js
- src/utils/wallet.ts
- The signatures to use when creating the input data for a p2sh utxo should be ordered by the account path pubkey
- When creating a p2sh input data we should ignore any signatures past the minimum since they will make the verification fail
> feat: sort p2sh signatures for multisig

- package-lock.json
- package.json
> chore: bump version v0.38.1

- package-lock.json
- package.json
> chore: bump v0.38.2

- __tests__/new_wallet.test.js
- __tests__/utils/wallet.test.js
- __tests__/wallet.test.js
- package-lock.json
- package.json
- src/new/wallet.js
- src/utils/wallet.ts
- src/wallet.js
> Release v0.38.2

- package-lock.json
- package.json
> chore: bump v0.39.0

- __tests__/__fixtures__/sample_txs.js
- __tests__/models/transaction.test.js
- __tests__/tokens_utils.js
- __tests__/wallet_utils.test.js
- package-lock.json
- package.json
- src/constants.js
- src/errors.js
- src/models/create_token_transaction.ts
- src/models/output.ts
- src/models/transaction.ts
- src/models/types.ts
- src/utils/helpers.ts
- src/wallet.js
> Release v0.39.0

- package-lock.json
- package.json
> chore: bump v0.40.0

- __tests__/models/partial_tx.test.js
- __tests__/models/partial_tx_inputdata.test.js
- index.js
- package-lock.json
- package.json
- setupTests.js
- src/errors.js
- src/models/output.ts
- src/models/p2pkh.ts
- src/models/p2sh.ts
- src/models/p2sh_signature.ts
- src/models/partial_tx.ts
- src/network.js
- src/new/sendTransaction.js
- src/new/wallet.js
- src/transaction.js
- src/wallet/partialTxProposal.ts
> Release v0.40.0

- __tests__/models/partial_tx.test.js
- src/models/partial_tx.ts
tests: test empty cases
- Should deserialize correctly if input metadata is empty
> fix: atomic swap empty metadata

- package-lock.json
- package.json
> chore: bump v0.40.1

- __tests__/models/partial_tx.test.js
- package-lock.json
- package.json
- src/models/partial_tx.ts
> Release v0.40.1

- package-lock.json
- package.json
> chore: bump v0.40.2

- package-lock.json
- package.json
- src/models/partial_tx.ts
- src/wallet/partialTxProposal.ts
> Release v0.40.2

- src/utils/address.ts
- src/wallet.js
> fix: add type to change output from old method

- package-lock.json
- package.json
> chore: bump v0.40.3

- package-lock.json
- package.json
- src/utils/address.ts
- src/wallet.js
> Release v0.40.3

- __tests__/integration/hathorwallet_facade.test.js
- Improves the test syntax for the #374 tests
> refactor: Integration test syntax improvements

- .github/workflows/main.yml
- codecov.yml
- jest.config.js
- Adds codecov to the project
- Closes #404
> chore: adds codecov to the project

- package-lock.json
- package.json
> chore: bump v0.40.4

- __tests__/models/transaction.test.js
- src/models/transaction.ts
- src/new/wallet.js
- src/transaction.js
- src/utils/transaction.ts
- src/wallet/wallet.ts
- Create a sign method on the transaction model
> feat: add sign method to transaction model

- package-lock.json
- package.json
> chore: bump v0.40.5

- package-lock.json
- package.json
Bump to v0.41.0
- [X ] Make sure you do not include new dependencies in the project unless strictly necessary and do not include dev-dependencies as production ones. More dependencies increase the possibility of one of them being hijacked and affecting us.
> chore: bump to v0.41.0

- .gitignore
- __tests__/hathorwallet.test.js
- __tests__/integration/atomic_swap.test.js
- __tests__/integration/hathorwallet_facade.test.js
- __tests__/models/transaction.test.js
- __tests__/token_details.test.js
- __tests__/transaction_utils.test.js
- __tests__/utils/wallet.test.js
- __tests__/wallet.test.js
- package-lock.json
- package.json
- src/models/transaction.ts
- src/new/wallet.js
- src/transaction.js
- src/utils/transaction.ts
- src/utils/wallet.ts
- src/wallet.js
- src/wallet/wallet.ts
> Release v0.41.0

- __tests__/encryption.test.js
- __tests__/hathorwallet.test.js
- __tests__/integration/hathorwallet_facade.test.js
- __tests__/integration/helpers/wallet.helper.js
- __tests__/utils/transaction.test.js
- src/new/wallet.js
- src/storage.js
- src/utils/transaction.ts
- Create the `getSignatures` method to sign all inputs from the loaded wallet
- Create more tests for the associated signing utils.
> feat: getSignatures method for HathorWallet

- __tests__/utils/wallet.test.js
- src/utils/wallet.ts
- Allow the `getPublicKeyFromXpub` method to convert xpub to publickey without derivation.
> feat: wallet utils for readonly p2sh

- package-lock.json
- package.json
> chore/bump v0.41.1

- __tests__/encryption.test.js
- __tests__/hathorwallet.test.js
- __tests__/integration/hathorwallet_facade.test.js
- __tests__/integration/helpers/wallet.helper.js
- __tests__/utils/transaction.test.js
- __tests__/utils/wallet.test.js
- package-lock.json
- package.json
- src/new/wallet.js
- src/storage.js
- src/utils/transaction.ts
- src/utils/wallet.ts
> Release v0.41.1

- package-lock.json
- package.json
- Bumps the library version to 0.42.0
> chore: bump to v0.42.0

- __tests__/hathorwallet.test.js
- __tests__/wallet.test.js
- jest-integration.config.js
- src/new/wallet.js
- src/wallet.js
- Create a method to calculate balance for all tokens in the history
- Use this method instead of calculating for individual tokens on `preProcessingWalletData`
> feat: calculate balance for all tokens

- package-lock.json
- package.json
> chore: bump version v0.42.1

- __tests__/hathorwallet.test.js
- __tests__/integration/hathorwallet_facade.test.js
- __tests__/models/queue.test.js
- __tests__/wallet.test.js
- jest-integration.config.js
- package-lock.json
- package.json
- src/models/queue.ts
- src/new/wallet.js
- src/wallet.js
> Release version v0.42.1

- package-lock.json
- package.json
> chore: bump to v0.43.0

- __tests__/__fixtures__/wallet.fixtures.ts
- __tests__/__mocks__/wallet.mock.ts
- __tests__/hathorwallet.test.js
- __tests__/pushNotification.test.ts
- __tests__/wallet/wallet.test.ts
- __tests__/websocket.test.js
- index.js
- jest.config.js
- package-lock.json
- package.json
- src/new/wallet.js
- src/pushNotification.ts
- src/wallet/api/walletApi.ts
- src/wallet/types.ts
- src/wallet/wallet.ts
- src/websocket/base.ts
> Release v0.43.0

- __tests__/hathorwallet.test.js
- __tests__/integration/hathorwallet_facade.test.js
- __tests__/wallet/wallet.test.ts
- jest-integration.config.js
- package-lock.json
- package.json
- src/api/txApi.js
- src/models/p2pkh.ts
- src/models/p2sh.ts
- src/new/wallet.js
- src/utils/buffer.ts
- src/utils/wallet.ts
- src/wallet/api/walletApi.ts
- src/wallet/types.ts
- src/wallet/wallet.ts
> Release v0.44.0

- __tests__/hathorwallet.test.js
- __tests__/integration/hathorwallet_facade.test.js
- __tests__/wallet/wallet.test.ts
- src/errors.js
- src/new/wallet.js
- src/wallet/api/walletApi.ts
- When a tx is not found on the fullnode, we should throw a specific Error so clients can handle it properly
> feat: throwing TxNotFound error when a tx is not found

- package-lock.json
- package.json
> chore: bump to v0.44.1

- __tests__/hathorwallet.test.js
- __tests__/integration/hathorwallet_facade.test.js
- __tests__/wallet/wallet.test.ts
- package-lock.json
- package.json
- src/errors.js
- src/new/wallet.js
- src/wallet/api/walletApi.ts
> Release v0.44.1

- package-lock.json
- package.json
> chore: bumped to v0.44.2

- package-lock.json
- package.json
> Release v0.44.2

- __tests__/hathorwallet.test.js
- __tests__/integration/hathorwallet_facade.test.js
- src/new/wallet.js
- Implement getTxById in the "new" wallet facade to match the wallet facade for wallet-service
> feat: implement getTxById new wallet facade

- package-lock.json
- package.json
- Bump to 0.45.0, by the addition of getTxById in the facade wallet
> chore: bump 0.45.0

- .eslintrc
- __tests__/hathorwallet.test.js
- __tests__/integration/hathorwallet_facade.test.js
- __tests__/pushNotification.test.ts
- __tests__/wallet/wallet.test.ts
- package-lock.json
- package.json
- setupTests.js
- src/new/wallet.js
- src/pushNotification.ts
- src/wallet/connection.ts
- src/wallet/wallet.ts
> Release 0.45.0

- package-lock.json
- package.json
- Bump to v0.46.0
- First integration with the Atomic Swap Service backend
> chore: bump 0.46.0

- __tests__/wallet/api/swapService.test.ts
- package-lock.json
- package.json
- src/config.ts
- src/models/types.ts
- src/wallet/api/swapService.ts
> Release v0.46.1

- __tests__/integration/hathorwallet_others.test.js
- src/storage/memory_store.ts
- solve the issue described in #480 
- force iterations on history to follow the timestamp order
> feat: ensure memory store history order

- package-lock.json
- package.json
- Update packages with known vulnerabilities
> chore: npm audit update deps

- package-lock.json
- package.json
> chore: bump version 1.0.0-rc1

- __tests__/integration/hathorwallet_facade.test.js
- __tests__/new/hathorwallet.test.js
- index.js
- src/new/wallet.js
- Add facade methods to abstract the storage
> feat: new facade method

- __tests__/integration/storage/storage.test.js
- __tests__/storage/leveldb/leveldb_store.test.js
- __tests__/storage/memory_store.test.js
- __tests__/storage/storage.test.js
- src/storage/storage.ts
- src/utils/storage.ts
- Remove utxos from "selected as input" map when their spent
> feat: clean selected as input utxos

- index.js
> feat: expose address utils

- __tests__/new/sendTransaction.test.js
- __tests__/storage/leveldb/leveldb_store.test.js
- __tests__/utils/utxo.test.js
- src/new/sendTransaction.ts
- src/storage/leveldb/utxo_index.ts
- src/storage/memory_store.ts
- src/types.ts
- src/utils/utxo.ts
- Implement the utxo selection algorithm
- Allow utxo selection algorithm to be configurable
> feat: utxo selection algo

- __tests__/new/sendTransaction.test.js
- src/new/sendTransaction.ts
- Check provided input token before checking validity
> fix: check input token in sendTransaction

- package-lock.json
- package.json
> chore: bump v1.0.0-rc2

- package-lock.json
- package.json
> chore: bumped to v0.46.2

- __tests__/new/sendTransaction.test.js
- __tests__/storage/storage.test.js
- index.js
- src/new/sendTransaction.ts
- src/storage/storage.ts
- src/types.ts
- src/utils/helpers.ts
- src/utils/tokens.ts
- src/utils/wallet.ts
- Create a method to validate user provided change address and throw appropriate error
- If no address is provided by the user, get one from the wallet.
- Change utils and functions that may use user provided change or choose one to use this new method.
- Expose number utils since it should be used on the wallets
> feat: validate user provided change address

- tsconfig.json
- Start generating typings when compiling
> feat: add ts typings

- __tests__/storage/common_store.test.js
- __tests__/storage/storage.test.js
- __tests__/utils/helpers.test.js
- __tests__/utils/tokens.test.js
- src/storage/leveldb/store.ts
- src/storage/leveldb/token_index.ts
- src/storage/memory_store.ts
- src/storage/storage.ts
- src/types.ts
- src/utils/helpers.ts
- src/utils/tokens.ts
- src/wallet/wallet.ts
Add token utilities required by the mobile wallet
- check that a token is registered by the uid
- get deposit percentage configuration for the current network
- validate token configuration string
- util to check for duplicate name or symbol on the registered tokens
> feat: new token utils

- __tests__/new/hathorwallet.test.js
- __tests__/storage/storage.test.js
- __tests__/utils/crypto.test.ts
- src/errorMessages.ts
- src/errors.ts
- src/new/wallet.js
- src/storage/leveldb/store.ts
- src/storage/memory_store.ts
- src/storage/storage.ts
- src/types.ts
- src/utils/crypto.ts
- src/utils/wallet.ts
- Generate account path key on the access data where possible.
- storage should have a method to get the account path key.
> feat: generate access data with account path key

- __tests__/integration/storage/leveldb.test.js
- __tests__/integration/storage/storage.test.js
- __tests__/models/transaction.test.js
- __tests__/storage/common_store.test.js
- __tests__/storage/leveldb/leveldb_store.test.js
- __tests__/storage/storage.test.js
- __tests__/utils/crypto.test.ts
- __tests__/utils/transaction.test.js
- __tests__/utils/utxo.test.js
- src/storage/leveldb/store.ts
- src/storage/leveldb/wallet_index.ts
- src/storage/memory_store.ts
- src/storage/storage.ts
- allow leveldb store to use any directory name
> feat: leveldb dir name

- __tests__/utils/wallet.test.js
- src/utils/wallet.ts
- src/wallet/wallet.ts
- Create a utility to get the walletId from the change path xpub.
> feat: wallet id util

- package-lock.json
- package.json
> bump version v1.0.0 rc3

- package-lock.json
- package.json
> chore: bump lib version to v0.47.0

- __tests__/integration/hathorwallet_facade.test.js
- __tests__/integration/helpers/wallet.helper.js
- __tests__/new/hathorwallet.test.js
- __tests__/storage/storage.test.js
- __tests__/utils/wallet.test.js
- src/new/wallet.js
- src/storage/storage.ts
- src/types.ts
- src/utils/wallet.ts
- src/wallet/wallet.ts
- Allow starting hardware wallets with the new storage scheme.
> feat: hardware wallet support

- package-lock.json
- package.json
> chore: bump version v1.0.0-rc4

- .babelrc
- .github/workflows/integration-test.yml
- __tests__/integration/hathorwallet_facade.test.js
- __tests__/integration/helpers/wallet.helper.js
- __tests__/models/address.test.js
- __tests__/new/hathorwallet.test.js
- __tests__/storage/leveldb/leveldb_store.test.js
- __tests__/storage/memory_store.test.js
- __tests__/storage/storage.test.js
- __tests__/utils/wallet.test.js
- __tests__/wallet/wallet.test.ts
- babel.config.js
- codecov.yml
- package-lock.json
- package.json
- src/models/address.ts
- src/new/wallet.js
- src/storage/leveldb/store.ts
- src/storage/memory_store.ts
- src/storage/storage.ts
- src/types.ts
- src/utils/tokens.ts
- src/utils/wallet.ts
- src/wallet/types.ts
- src/wallet/wallet.ts
> Release v1.0.0-rc4

- package-lock.json
- package.json
> Release v1.0.0-rc5

- index.js
- Reference to Atomic Swap file must have correct path
> fix: Swap file reference

- src/wallet/wallet.ts
- We should use the new `signMessage` method introduced in https://github.com/HathorNetwork/hathor-wallet-lib/pull/546
> refactor: use crypto sign

- package-lock.json
- package.json
> chore: bumped to v1.0.0-rc6

- __tests__/integration/hathorwallet_facade.test.js
- __tests__/models/transaction.test.js
- __tests__/new/hathorwallet.test.js
- __tests__/swapService/swapConnection.test.ts
- __tests__/utils/crypto.test.ts
- __tests__/wallet/api/walletApi.test.ts
- __tests__/wallet/wallet.test.ts
- __tests__/websocket/websocket.test.ts
- index.js
- package-lock.json
- package.json
- src/connection.ts
- src/constants.ts
- src/models/create_token_transaction.ts
- src/models/network.ts
- src/models/transaction.ts
- src/models/types.ts
- src/new/connection.ts
- src/new/wallet.js
- src/swapService/swapConnection.ts
- src/types.ts
- src/utils/crypto.ts
- src/utils/helpers.ts
- src/utils/transaction.ts
- src/wallet/api/walletApi.ts
- src/wallet/types.ts
- src/wallet/wallet.ts
- src/websocket/base.ts
- src/websocket/index.ts
> Release v1.0.0-rc6

- __tests__/utils/helpers.test.js
- __tests__/utils/transaction.test.js
- babel.config.js
- package.json
- src/storage/leveldb/address_index.ts
- src/storage/leveldb/history_index.ts
- src/storage/leveldb/store.ts
- src/storage/leveldb/token_index.ts
- src/storage/leveldb/utxo_index.ts
- src/storage/leveldb/wallet_index.ts
- src/utils/helpers.ts
- src/utils/storage.ts
- src/utils/transaction.ts
- Do not delete registered tokens when cleaning the wallet storage
- Add utilities required by the wallet desktop
- emit the correct event for partial ui update
> feat: wallet desktop utils

- __tests__/utils/helpers.test.js
- __tests__/utils/transaction.test.js
- babel.config.js
- package-lock.json
- package.json
- src/storage/leveldb/address_index.ts
- src/storage/leveldb/history_index.ts
- src/storage/leveldb/store.ts
- src/storage/leveldb/token_index.ts
- src/storage/leveldb/utxo_index.ts
- src/storage/leveldb/wallet_index.ts
- src/utils/helpers.ts
- src/utils/storage.ts
- src/utils/transaction.ts
- tsconfig.json
> Release v1.0.0-rc7

- package-lock.json
- package.json
- Bump release candidate to rc8
> chore: bump v1.0.0-rc8

- package-lock.json
- package.json
> Release v1.0.0-rc8

- package-lock.json
- package.json
> chore: bump v1.0.0

- package-lock.json
- package.json
> Release version v1.0.0

- __tests__/storage/storage.test.js
- src/new/wallet.js
- src/storage/leveldb/utxo_index.ts
- src/storage/memory_store.ts
- src/utils/storage.ts
- src/utils/transaction.ts
- Include merged mining blocks when checking for heightlock
> fix: check for block using utils

- package-lock.json
- package.json
> chore: bump v1.0.1

- __tests__/storage/storage.test.js
- package-lock.json
- package.json
- src/new/wallet.js
- src/storage/leveldb/utxo_index.ts
- src/storage/memory_store.ts
- src/utils/storage.ts
- src/utils/transaction.ts
> Release v1.0.1

- src/new/wallet.js
- Do not stop wallet when running changeServer
> fix: change server

- src/new/sendTransaction.ts
- src/utils/helpers.ts
- src/utils/tokens.ts
- Create token, mint tokens, and melt tokens should use the best utxo selection algorithm by default.
> feat: use best utxo selection algorithm by default for tokens methods (create, mint, melt)

- src/utils/storage.ts
- Retry any failures on the token api when syncing history
> feat: retry token api on history sync

- package-lock.json
- package.json
> chore: bump version v1.0.2

- __tests__/storage/leveldb/leveldb_store.test.js
- __tests__/storage/memory_store.test.js
- __tests__/storage/storage.test.js
- __tests__/wallet/wallet.test.ts
- package-lock.json
- package.json
- src/new/sendTransaction.ts
- src/new/wallet.js
- src/storage/leveldb/store.ts
- src/storage/leveldb/token_index.ts
- src/storage/memory_store.ts
- src/storage/storage.ts
- src/types.ts
- src/utils/helpers.ts
- src/utils/storage.ts
- src/utils/tokens.ts
> Release v1.0.2

- __tests__/integration/helpers/wallet.helper.js
- setupTests-integration.js
- We must mine at least one block before starting the integration tests, so the genesis reward is unlocked.
> tests: wait until the first block is mined before start the integration tests, to release the genesis reward

- package-lock.json
- package.json
> bump: wallet-lib v1.0.3

- package-lock.json
- package.json
> chore: bump version v1.0.4

- package-lock.json
- package.json
- Bump lib version to v1.1.0
- PRs for this bump:
- https://github.com/HathorNetwork/hathor-wallet-lib/pull/596
- https://github.com/HathorNetwork/hathor-wallet-lib/pull/598
> chore: bump version to v1.1.0

- __tests__/integration/hathorwallet_facade.test.js
- __tests__/utils/tokens.test.js
- package-lock.json
- package.json
- src/new/wallet.js
- src/utils/tokens.ts
- Release v1.1.0
- https://github.com/HathorNetwork/hathor-wallet-lib/pull/596
- https://github.com/HathorNetwork/hathor-wallet-lib/pull/598
> Release v1.1.0

- src/models/output.ts
- src/utils/scripts.ts
- Move parse script method to the utils scripts file.
> refactor: move parse script method from output model to an utils method

- package-lock.json
- package.json
- https://github.com/HathorNetwork/hathor-wallet-lib/pull/605
- https://github.com/HathorNetwork/hathor-wallet-lib/pull/608
> bump: v1.2.0

- __tests__/api/health.test.ts
- package-lock.json
- package.json
- src/api/health.js
- src/models/output.ts
- src/utils/scripts.ts
- https://github.com/HathorNetwork/hathor-wallet-lib/pull/605
- https://github.com/HathorNetwork/hathor-wallet-lib/pull/608
> Release: v1.2.0

- src/api/nano.ts
- src/errorMessages.ts
- src/errors.ts
- Add nano contract APIs to send requests to the full node.
- Add an error to throw in case of any error in the requests.
Note: CI is broken because this PR just adds the APIs to send requests to the full node. There are integration tests in another [PR](https://github.com/HathorNetwork/hathor-wallet-lib/pull/604) that cover all this code. This will be merged with the codecov CI broken and the other PR will guarantee that everything is fine.
> feat: add nano apis and error for requests

- package-lock.json
- package.json
> chore: bump v1.2.1

- __tests__/new/hathorwallet.test.js
- __tests__/utils/address.test.ts
- src/new/wallet.js
- src/utils/address.ts
This change will enable the wallet mobile to show Nano Contract information from token transaction details view.
- Should add some Nano Contract properties on ITxHistory
- Should add utility to parse pubkey to address from it
> feat: add some nc properties on tx history model

- __tests__/storage/leveldb/leveldb_store.test.js
- __tests__/storage/memory_store.test.js
- src/storage/leveldb/address_index.ts
- src/storage/leveldb/history_index.ts
- src/storage/leveldb/nanocontract_index.ts
- src/storage/leveldb/store.ts
- src/storage/leveldb/token_index.ts
- src/storage/leveldb/utils.ts
- src/storage/leveldb/utxo_index.ts
- src/storage/leveldb/wallet_index.ts
- src/storage/memory_store.ts
- src/storage/storage.ts
- src/types.ts
- src/utils/storage.ts
- Should add Nano Contract operations to storage, namely read and register operations.
> feat: add nano contract operations to storage

- package-lock.json
- package.json
> chore: bump v1.3.0

- __tests__/integration/nanocontracts/bet.test.js
- src/lib.ts
- src/nano_contracts/deserializer.ts
- src/nano_contracts/parser.ts
- Add deserializer and parser classes to help showing nano contract arguments in the explorer.
> feat: classes to deserialize and parse nano contract arguments and object to show in the explorer

- package-lock.json
- package.json
> chore: bump lib version to v1.4.0

- __tests__/integration/nanocontracts/bet.test.js
- package-lock.json
- package.json
- src/lib.ts
- src/nano_contracts/deserializer.ts
- src/nano_contracts/parser.ts
- Release lib v1.4.0
Pull requests included:
- https://github.com/HathorNetwork/hathor-wallet-lib/pull/606
- https://github.com/HathorNetwork/hathor-wallet-lib/pull/625
> Release v1.4.0

- __tests__/new/hathorwallet.test.js
- __tests__/utils/transaction.test.js
- src/nano_contracts/builder.ts
- src/nano_contracts/utils.ts
- src/new/wallet.js
- src/storage/storage.ts
- src/types.ts
- src/utils/transaction.ts
- Allow externally signed nano contract transactions.
> feat: nc external signing method

- package-lock.json
- package.json
> chore: bump v1.4.1

- __tests__/new/hathorwallet.test.js
- __tests__/utils/transaction.test.js
- package-lock.json
- package.json
- src/nano_contracts/builder.ts
- src/nano_contracts/utils.ts
- src/new/wallet.js
- src/storage/storage.ts
- src/types.ts
- src/utils/transaction.ts
> Release v1.4.1

- .github/PULL_REQUEST_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE/feature.md
- .github/PULL_REQUEST_TEMPLATE/release.md
- codecov.yml
- The repository files should be adapted to conform with [its New Release Process](https://github.com/HathorNetwork/ops-tools/pull/806)
As described on the release process guidelines, _release candidate versions_ will be an exception for this repository, so the _rc_ template was not included on this PR.
Whenever a release candidate is necessary, the steps on the guidelines document should be followed manually.
> chore: New release process

- __tests__/new/hathorwallet.test.js
- src/new/wallet.js
- src/types.ts
- It should add first_block property to ITxHistory
- It should return firstBlock property on getTxHistory
> feat: add first_block to ITxHistory and getTxHistory

- package-lock.json
- package.json
- Upgrades the `isomorphic-ws` dependency from `4.0.1` to `5.0.0`
According to [the library's changelogs](https://github.com/heineiuo/isomorphic-ws/blob/master/CHANGELOG.md) and [release notes](https://github.com/heineiuo/isomorphic-ws/releases) there were no breaking changes on this major update.
> chore: upgrades `isomorphic-ws`

- package-lock.json
- package.json
- Upgrades `typescript` and its related dependencies
None of the errors mentioned in [the `v5` release notes](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#breaking-changes-and-deprecations) for the breaking changes were found during the tests.
Tests on the Desktop Wallet also have shown no issues with this upgrade.
> chore: Upgrades `typescript` and related

- package-lock.json
- package.json
> chore: bump v1.6.0

- __tests__/integration/hathorwallet_facade.test.js
- __tests__/new/hathorwallet.test.js
- src/new/wallet.js
- src/utils/tokens.ts
- Allow data outputs on mint and melt operations
> feat: token admin data

- src/api/nano.ts
- Add support for 'before' parameter in the nano history API
> feat: add support for 'before' parameter in the nano history API

- __tests__/integration/hathorwallet_facade.test.js
- __tests__/new/hathorwallet.test.js
- src/api/nano.ts
- src/new/wallet.js
- src/utils/tokens.ts
Start the release process for version `1.7.0`.
This PR will merge any changes on `release-candidate` into `release` branch.
PRs for this release:
- https://github.com/HathorNetwork/hathor-wallet-lib/pull/673
- https://github.com/HathorNetwork/hathor-wallet-lib/pull/674
> Release v1.7.0

- package-lock.json
- package.json
> chore: bump to v1.7.0

- package-lock.json
- package.json
- Update `master` branch with `release`
> update master branch with release

- __tests__/utils/transaction.test.js
- src/constants.ts
- src/utils/transaction.ts
- Add POA block version
- Add POA block to helpers
> feat: poablock in helpers

- __tests__/integration/atomic_swap.test.js
- __tests__/integration/hathorwallet_facade.test.js
- __tests__/integration/hathorwallet_others.test.js
- __tests__/integration/nanocontracts/bet.test.js
- __tests__/integration/storage/storage.test.js
- __tests__/models/partial_tx.test.js
- __tests__/new/sendTransaction.test.js
- __tests__/utils/tokens.test.js
- __tests__/wallet/partialTxProposal.test.ts
- src/constants.ts
- src/models/partial_tx.ts
- src/nano_contracts/builder.ts
- src/new/sendTransaction.ts
- src/new/wallet.js
- src/storage/leveldb/utxo_index.ts
- src/storage/memory_store.ts
- src/storage/storage.ts
- src/utils/tokens.ts
- src/utils/transaction.ts
- src/wallet/partialTxProposal.ts
- src/wallet/sendTransactionWalletService.ts
- src/wallet/wallet.ts
- Change all instances of `HATHOR_TOKEN_CONFIG.uid` to `HATHOR_TOKEN_UID`
> feat: use htr uid const where possible

- __tests__/storage/leveldb/leveldb_store.test.js
- __tests__/storage/memory_store.test.js
- __tests__/storage/storage.test.js
- src/config.ts
- src/constants.ts
- src/models/partial_tx.ts
- src/new/wallet.js
- src/storage/leveldb/token_index.ts
- src/storage/memory_store.ts
- src/storage/storage.ts
- src/types.ts
- src/utils/storage.ts
This is part of development of this [issue](https://github.com/HathorNetwork/internal-issues/issues/330).
- Create a way to configure the native token.
- Remove the constant `HATHOR_TOKEN_CONFIG`.
- Remove the default hathor token config from storage.
> feat: native token config

- __tests__/integration/nanocontracts/bet.test.js
- src/nano_contracts/utils.ts
- Add method to check if a transaction is a nano contract create tx
> feat: add method to check if a tx is a nano contract create

- __tests__/utils/numbers.test.ts
- src/storage/storage.ts
- src/types.ts
- src/utils/numbers.ts
- Allow the prettyValue util to use any number of decimal places
- Create a storage util to get the node decimal place config
> feat: configurable decimal places

- package-lock.json
- package.json
> chore: bump v1.8.0

- __tests__/utils/helpers.test.js
- src/utils/helpers.ts
- Helper method to get lib network from the full node network.
> feat: add method to get network from full node network

- src/api/metadataApi.ts
- src/models/queue.ts
- src/storage/leveldb/nanocontract_index.ts
- src/storage/leveldb/token_index.ts
- src/wallet/wallet.ts
- Fixes lint [consistent-return](https://eslint.org/docs/latest/rules/consistent-return) rule
> fix: consistent-return rule

- src/wallet/wallet.ts
- Fixes [`no-cond-assign`](https://eslint.org/docs/latest/rules/no-cond-assign) rule
> fix: no-cond-assign rule

- src/models/queue.ts
- Fixes [`no-unused-expressions`](https://eslint.org/docs/latest/rules/no-unused-expressions) rule
> fix: no-unused-expressions rule

- src/connection.ts
- src/errors.ts
- src/models/transaction.ts
- src/nano_contracts/builder.ts
- src/nano_contracts/deserializer.ts
- src/nano_contracts/nano_contract.ts
- src/nano_contracts/serializer.ts
- src/nano_contracts/types.ts
- src/storage/leveldb/store.ts
- src/storage/leveldb/wallet_index.ts
- src/storage/memory_store.ts
- src/storage/storage.ts
- src/types.ts
- src/utils/connection.ts
- src/utils/crypto.ts
- src/utils/storage.ts
- src/utils/tokens.ts
- src/wallet/mineTransaction.ts
- src/wallet/wallet.ts
This PR is composed of two separate commits for an easier scoped review: one commit for the nano-contracts code and the other for the remaining lib code.
- Fixes [`@typescript-eslint/no-explicit-any`](https://typescript-eslint.io/rules/no-explicit-any/) rule
> fix: no-explicit-any rule

- src/new/wallet.js
- src/utils/storage.ts
- src/utils/tokens.ts
Requires:
- #703 
- Fixes [`no-promise-executor-return`](https://eslint.org/docs/latest/rules/no-promise-executor-return) rule
> fix: no-promise-executor-return rule

- __tests__/api/metadata.test.ts
- src/api/metadataApi.ts
- Solves the consistent return issue found in https://github.com/HathorNetwork/hathor-wallet-lib/pull/680#discussion_r1661284287
- Adds unit tests to the `getDagMetadata` method
> refactor: Consistent return for `getDagMetadata`

- package-lock.json
- package.json
> chore: bump v1.9.0

- __tests__/api/txMining.test.ts
- __tests__/api/version.test.ts
- __tests__/integration/hathorwallet_facade.test.ts
- __tests__/utils/wallet.test.ts
- __tests__/wallet/mineTransaction.test.ts
- Fixes the [`jest/no-conditional-expect` rule](https://github.com/jest-community/eslint-plugin-jest/blob/main/docs/rules/no-conditional-expect.md)
> style: `jest/no-conditional-expect` rule

- __tests__/swapService/swapConnection.test.ts
- __tests__/wallet/api/swapService.test.ts
- __tests__/wallet/partialTxProposal.test.ts
- Fixes the [`ban-ts-comment` rule](https://typescript-eslint.io/rules/ban-ts-comment/)
> style: `@typescript-eslint/ban-ts-comment` rule

- __tests__/wallet/wallet.test.ts
- Fixes the [`no-explicit-any` rule](https://typescript-eslint.io/rules/no-explicit-any/)
> style: `@typescript-eslint/no-explicit-any` rule

- __tests__/integration/helpers/wallet.helper.ts
- Fixes the [`no-async-executor` rule](https://eslint.org/docs/latest/rules/no-async-promise-executor)
> style: `no-async-promise-executor` rule

- .eslintrc.js
- __tests__/integration/atomic_swap.test.ts
- __tests__/integration/helpers/wallet.helper.ts
- __tests__/integration/nanocontracts/bet.test.ts
- __tests__/integration/storage/leveldb.test.ts
- __tests__/integration/storage/storage.test.ts
- __tests__/integration/utils/placeholder-logger.util.ts
- __tests__/models/network.test.ts
- __tests__/models/p2pkh.test.ts
- __tests__/models/p2sh.test.ts
- __tests__/models/partial_tx.test.ts
- __tests__/new/hathorwallet.test.ts
- __tests__/new/sendTransaction.test.ts
- __tests__/storage/storage.test.ts
- __tests__/utils/address.test.ts
- __tests__/utils/crypto.test.ts
- __tests__/utils/transaction.test.ts
- __tests__/wallet/partialTxProposal.test.ts
- __tests__/wallet/wallet.test.ts
- src/wallet/types.ts
- Fixes linting items that are easy to understand and don't change logic too much
- Removes unused imports, functions and variables
> style(tests): Simple lint fixes

- .github/workflows/integration-test.yml
- .github/workflows/release-sync.yml
- The integration test workflow triggers should be equal to the main tests
- Removes leftover code from the `release-sync` workflow
> fix: Workflow triggers

- __tests__/__fixtures__/tx_history.ts
- __tests__/storage/common_store.test.ts
- __tests__/storage/leveldb/leveldb_store.test.ts
- __tests__/storage/storage.test.ts
- __tests__/utils/storage.test.ts
- __tests__/utils/utxo.test.ts
- src/api/axiosInstance.ts
- src/api/txApi.ts
- src/api/wallet.ts
- src/types.ts
Depends on https://github.com/HathorNetwork/hathor-wallet-lib/pull/719
See https://github.com/HathorNetwork/internal-issues/issues/363.
This PR makes some simple improvements in typing in multiple files that will aid implementing the `OutputValueType` refactor from `number` to `bigint`.
- Add some missing parameter/return types in functions.
- Add some missing properties in test fixtures.
- Rename `api/txApi.js` and `api/wallet.js` files to `.ts`, enabling typing in them.
- Fix typing of some `IHistoryTx` properties.
- No behavior should change.
> refactor: typing improvements

- package-lock.json
- package.json
- Bump package version to v1.10.0
> chore: bump package to v1.10.0

- __tests__/stream.test.ts
- src/sync/stream.ts
- Treat begin stream event with no action.
> chore: treat begin stream event

- package-lock.json
- package.json
- Merge this branch that is up to date with `release` into `master` to create common history
> chore: sync release v1.10.0

- src/connection.ts
- src/new/connection.ts
- src/sync/stream.ts
- Send history stream events to queue for processing.
- Process each item sequentially while allowing aborts.
- Implement the client side of the flow control https://github.com/HathorNetwork/hathor-core/pull/1126
> feat: stream to queue implementation with flow control

- release.sh
This PR introduces a release.sh script designed to automate all essential tasks and checks required to build and release the project to npm. The goal is to standardize the release process, ensuring consistency and safety, regardless of who performs the release.
1. Script that releases a new version of the lib in npm.
> chore(release): Add script to release a new version

- package-lock.json
- package.json
> chore: bump v1.12.0

- package-lock.json
- package.json
> chore: bump 1.12.1

- package-lock.json
- package.json
- src/sync/gll.ts
- src/sync/stream.ts
- Merge release changes back into master
> chore: sync release v1.12.1

- __tests__/models/priority_queue.test.ts
- __tests__/models/promise_queue.test.ts
- babel.config.js
- package-lock.json
- package.json
- src/models/priority_queue.ts
- src/models/promise_queue.ts
- src/new/wallet.js
- src/sync/gll.ts
- Implement a promise queue over a priority queue.
- Remove the queue-promise dependency.
- Change GLL to be a promise queue instance.
> feat: promise queue implementation

- .github/workflows/release-sync.yml
- Adapt sync release workflow
- Use the release creator as assignee
> feat: adaptation on sync release github workflow

- .github/workflows/release-sync.yml
- __tests__/models/priority_queue.test.ts
- __tests__/models/promise_queue.test.ts
- __tests__/storage/storage.test.ts
- __tests__/stream.test.ts
- babel.config.js
- package-lock.json
- package.json
- release.sh
- src/models/priority_queue.ts
- src/models/promise_queue.ts
- src/new/connection.ts
- src/new/wallet.js
- src/storage/storage.ts
- src/sync/gll.ts
- src/sync/stream.ts
Start the release process for version `v1.13.0`.
> Release v1.13.0

- package-lock.json
- package.json
> chore: bump v1.13.0

- __tests__/integration/configuration/docker-compose.yml
- __tests__/integration/helpers/wallet.helper.ts
- __tests__/integration/nanocontracts/bet.test.ts
- src/api/nano.ts
- src/nano_contracts/types.ts
- Add `block_hash` and `block_height` parameters to the nano state API.
- Update nano docker image to the latest in the integration tests.
> feat: add block_hash and block_height parameters to the nano state API

- __tests__/integration/hathorwallet_facade.test.ts
- src/new/wallet.js
- `getMintAuthority` and `getMeltAuthority` should return available utxos
> feat: only select available authorities

- package-lock.json
- package.json
> chore: bump v1.14.0

- package-lock.json
- package.json
> bump: v1.14.1

- __tests__/integration/nanocontracts/bet.test.ts
- src/utils/storage.ts
- Add address metadata considering nano contract transaction caller.
> feat: consider nano caller to the address metadata in the storage

- package-lock.json
- package.json
> chore: bump v2.0.0

- package-lock.json
- package.json
> chore: bump v2.0.1

- __tests__/integration/hathorwallet_others.test.ts
- src/new/wallet.js
- src/utils/storage.ts
> feat: process simple metadata changes

- package-lock.json
- package.json
> chore: bump lib to v2.1.0

- __tests__/integration/hathorwallet_facade.test.ts
- __tests__/integration/nanocontracts/bet.test.ts
- src/api/schemas/txApi.ts
Start the release process for version `2.1.1`.
> Release v2.1.1

- package-lock.json
- package.json
> chore: bump package to v2.1.1

- src/lib.ts
- We need to export nano contract types
- We need to export model types
> feat: export missing types

- __tests__/wallet/walletSchemas.test.ts
- src/wallet/api/schemas/walletApi.ts
- Fix JWT token validation in `authTokenResponseSchema` to properly validate JWT format
> fix: auth token response schema

- package-lock.json
- package.json
> chore: bumped to v2.2.0

- __tests__/utils/transaction.test.ts
- package-lock.json
- src/utils/transaction.ts
> feat: OCB getTxType

- __tests__/integration/api.test.ts
- __tests__/utils/transaction.test.ts
- package-lock.json
- package.json
- src/api/featuresApi.ts
- src/lib.ts
- src/utils/transaction.ts
Start the release process for version `2.3.0`.
> Release process 2.3.0

- package-lock.json
- package.json
> chore: bump version v2.3.0

- src/new/sendTransaction.ts
- src/new/wallet.js
Start the release process for version `v2.3.1`.
> Release v2.3.1

- package-lock.json
- package.json
> chore: bump v2.3.1

- __tests__/nano_contracts/deserializer.test.ts
- __tests__/nano_contracts/serializer.test.ts
- __tests__/utils/leb128.test.ts
- src/nano_contracts/deserializer.ts
- src/nano_contracts/serializer.ts
- src/nano_contracts/types.ts
- src/utils/leb128.ts
https://github.com/HathorNetwork/nano-hathor-core/pull/167
- Add the new VarInt to the nano contract serializers
> feat: varint type for nano contract argument

- package-lock.json
- package.json
> chore: bumped to v2.3.2

- __tests__/integration/configuration/bet.py
- Update bet blueprint for on-chain-blueprint integration tests
> chore: update bet blueprint

- __tests__/integration/configuration/bet.py
- __tests__/integration/configuration/docker-compose.yml
- __tests__/integration/nanocontracts/bet.test.ts
- __tests__/new/hathorwallet.test.ts
- __tests__/utils/transaction.test.ts
- src/api/schemas/txApi.ts
- src/constants.ts
- src/headers/base.ts
- src/models/create_token_transaction.ts
- src/models/transaction.ts
- src/nano_contracts/builder.ts
- src/nano_contracts/header.ts
- src/nano_contracts/parser.ts
- src/nano_contracts/utils.ts
- src/new/wallet.js
- src/schemas.ts
- src/types.ts
- src/utils/helpers.ts
- src/utils/storage.ts
- src/utils/transaction.ts
> feat: change nc caller pubkey to address

- src/types.ts
- Remove unused types that were necessary with the LevelDB (that was already removed).
> refactor: remove unused types

- package-lock.json
- package.json
> chore: bump lib to v2.4.0

- package-lock.json
- package.json
> chore: bump version 2.5.0

- package-lock.json
- package.json
> chore: bump package to v2.5.1

- package-lock.json
- package.json
> chore: bump package to v2.5.2

- package-lock.json
- package.json
> chore: bump package to v2.6.0

- __tests__/wallet/wallet.test.ts
- src/wallet/types.ts
- src/wallet/wallet.ts
- Create method to get server URL in the wallet service facade
Note: we already have this method in the old facade
> feat: add getServerUrl to wallet service facade

- __tests__/wallet/wallet.test.ts
- src/wallet/api/schemas/walletApi.ts
- src/wallet/sendTransactionWalletService.ts
- src/wallet/wallet.ts
- src/wallet/walletServiceStorageProxy.ts
- We must have the same signatures for the `prepareCreateNewToken` method in both facades
- We must fix the `ncContext` schema validation from `address` to `caller_id`
- We must fix `getAddressIndex` to be async and request the index from the wallet-service instead of the local `newAddresses` cache (which is a bug)
> refactor: create token options

- __tests__/wallet/wallet.test.ts
- src/lib.ts
- src/nano_contracts/utils.ts
- src/wallet/sendTransactionWalletService.ts
- src/wallet/types.ts
- src/wallet/wallet.ts
- Add new methods to the `IHathorWallet` facade
- Export types from `wallet/types.ts`
> feat: complete IHathorWallet interface with new methods for typing

- package-lock.json
- package.json
> chore: bump package to v2.7.0

- src/wallet/sendTransactionWalletService.ts
Start the release process for version `2.7.1`.
> Release v2.7.1

- __tests__/integration/configuration/blueprints/full_blueprint.py
- __tests__/integration/configuration/blueprints/test_children.py
- __tests__/integration/configuration/blueprints/test_parent.py
- __tests__/integration/nanocontracts/authority.test.ts
- __tests__/integration/nanocontracts/bet.test.ts
- __tests__/integration/nanocontracts/full_blueprint.test.ts
- __tests__/integration/nanocontracts/parent_children.test.ts
- __tests__/wallet/wallet.test.ts
- src/nano_contracts/builder.ts
- src/nano_contracts/types.ts
- src/nano_contracts/utils.ts
- src/wallet/wallet.ts
Start the release process for version `2.8.0`.
> Release v2.8.0

- package-lock.json
- package.json
> chore: bump package to v2.8.0

- __tests__/integration/configuration/docker-compose.yml
- __tests__/integration/hathorwallet_others.test.ts
- src/schemas.ts
- src/types.ts
- src/wallet/api/schemas/walletApi.ts
- src/wallet/types.ts
Start the release process for version `2.8.1`.
> Start release process for v2.8.1

- package-lock.json
- package.json
> chore: bump package to v2.8.1

- __tests__/integration/nanocontracts/full_blueprint.test.ts
- src/nano_contracts/fields/collection.ts
- Fix bytes read in the fromBuffer method from the collection field
> fix: fix bytesRead value from fromBuffer method
